### ISSUE TITLE
Tumor extension deduplicating

### ISSUE THREAD

**Issue by denyskaduk** [OHDSI/OncologyWG#102]
naaccr_item '2810’ - CS Extension (Identifies contiguous growth (extension) of the primary tumor), naaccr_item ‘772’  - EOD Primary Tumor (is used to classify contiguous growth (extension) of the primary tumor), as we can see this two items describe same thing and  it can be deduplicated and their values can be deduplicated too

variable_description | concept_name | vocabulary_id | concept_class_id | concept_code | suggested_standard_concept_name | standard_concept_code | standard_vocabulary_id
-- | -- | -- | -- | -- | -- | -- | --
  | CS Extension | NAACCR | NAACCR Variable | 2810 | CS Extension | OMOP_code | NAACCR
  | EOD Primary Tumor | NAACCR | NAACCR Variable | 772 | CS Extension | OMOP_code | NAACCR
  |   |   |   |   |   |   |  
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | small_intestine@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | esophagus_gejunction@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | stomach@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
CS Extension | OBSOLETE DATA RETAINED AND REVIEWED V0203\|See code 000\|\|(Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | gist_stomach@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
EOD Primary Tumor | In situ, intraepithelial, noninvasive\|(Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | stomach@772@000 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
EOD Primary Tumor | In situ, intraepithelial, non-invasive, high-grade dysplasia\|(Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | esophagus_including_ge_junction_squamous@772@000 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
EOD Primary Tumor | In situ, intraepithelial, non-invasive, high-grade dysplasia\|(Adeno)carcinoma, noninvasive, in a polyp | NAACCR | NAACCR Value | esophagus_gejunction@772@000 | (Adeno)carcinoma, noninvasive, in a polyp | OMOP_code | NAACCR
  |   |   |   |   |   |   |  
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | rectum@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | colon@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | appendix@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR
CS Extension | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | carcinoid_appendix@2810@050 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR
EOD Primary Tumor | In situ, intraepithelial, noninvasive\|(Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | small_intestine@772@000 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR
EOD Primary Tumor | In situ, intraepithelial, noninvasive\|(Adeno)carcinoma, noninvasive, in a polyp or adenoma | NAACCR | NAACCR Value | net_appendix@772@000 | (Adeno)carcinoma, noninvasive, in a polyp or adenoma | OMOP_code | NAACCR

**Comment by jeremywarner** [comment]
Hi if you’re choosing between “CS” and “EOD” variables, please keep “EOD” (Extent of Disease) which is a current system. CS (collaborative stage) has been phased out; useful for historic data but not going forward.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by denyskaduk** [comment]
Hello, @jeremywarner,  don't worry we won't delete anything. We do the NAACCR concepts  non-standard and create a new standard concept or map them to standard one. As in example above will be create a new standard and we can do a new name or keep one from non-standard concept. As both “CS” and “EOD” variables  will be non-standard we will put them in MEASUREMENT table as SOURCE_CONCEPT_ID and the new standard will be placed in MEASUREMENT_CONCEPT_ID.

**Comment by cgreich** [comment]
>  create a new standard concept 
@denyskaduk: Usually, we don't create Standard Concepts out of the blue, but we promote some Concept to Standards and some leave as non-standard. Creating brand new Concepts would mean to build an Extension, and so far we haven't pulled the plug and decided to do that.

So, please make the EODs Standard and the CS ones non-standard, and create a relationship between them.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
