### ISSUE TITLE
TNM Staging

### ISSUE THREAD

**Issue by denyskaduk** [OHDSI/OncologyWG#103]
Should we treat pathological and clinical stage values as the same concept , like we already have in LOINC?

variable_description | concept_name | vocabulary_id | concept_class_id | concept_code | suggested_standard_concept_name | standard_concept_code | standard_vocabulary_id
-- | -- | -- | -- | -- | -- | -- | --
(TNM Tumor case) |   |   |   |   |   |   |  
TNM Path T | pT1a | NAACCR | NAACCR Value | 880@p1A | T1a | LA3636-3 | LOINC
TNM Clin T | cT1a | NAACCR | NAACCR Value | 940@c1A | T1a | LA3636-3 | LOINC
(TNM Metastatic case) |   |   |   |   |   |   |  
CS Mets at DX | Stated as M1a with no other information on distant metastases | NAACCR | NAACCR Value | merkel_cell_scrotum@2850@20 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastases | NAACCR | NAACCR Value | merkel_cell_penis@2850@20 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastases | NAACCR | NAACCR Value | merkel_cell_vulva@2850@20 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastases | NAACCR | NAACCR Value | merkel_cell_skin@2850@20 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | lung@2850@26 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | melanoma_ciliary_body@2850@52 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | colon@2850@27 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | rectum@2850@27 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | melanoma_iris@2850@52 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | melanoma_choroid@2850@52 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | prostate@2850@20 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on metastasis | NAACCR | NAACCR Value | melanoma_skin@2850@55 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on metastasis | NAACCR | NAACCR Value | lymphoma_ocular_adnexa@2850@35 | M1A | LA4627-1 | LOINC
CS Mets at DX | Stated as M1a with no other information on metastasis | NAACCR | NAACCR Value | testis@2850@30 | M1A | LA4627-1 | LOINC
CS Mets at DX | OBSOLETE DATA CONVERTED V0203\|See code 27\|\|Stated as M1a with no other information on distant metastases | NAACCR | NAACCR Value | colon@2850@22 | M1A | LA4627-1 | LOINC
CS Mets at DX | Distant metastasis to lung only\|\|Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | bone@2850@30 | M1A | LA4627-1 | LOINC
CS Mets at DX | Distant metastasis to single lesion, NOS\|\|Stated as M1a with no other information on metastasis | NAACCR | NAACCR Value | retinoblastoma@2850@35 | M1A | LA4627-1 | LOINC
CS Mets at DX | For mucinous tumors only:\| Intraperitoneal metastasis BEYOND the right lower quadrant, including pseudomyxoma peritonei\|\|Stated as M1a with no other information on distant metastasis | NAACCR | NAACCR Value | appendix@2850@05 | M1A | LA4627-1 | LOINC
TNM Clin M | cM1a | NAACCR | NAACCR Value | 960@c1A | M1A | LA4627-1 | LOINC
TNM Path M | pM1a | NAACCR | NAACCR Value | 900@p1A | M1A | LA4627-1 | LOINC

**Comment by sratwani** [comment]
@dimshitc looks like we discussed this today and Rimma recommended that we **should not** treat pathological and clinical stage values as the same concept and should not collapse them. Can this issue be closed?
