### ISSUE TITLE
Add 'Registry' type concept to all domains.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#11]
concept_id |concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code |valid_start_date | valid_end_date | invalid_reason
------------ | -------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------
next concept id|Tumor Registry|Type Concept|Meas Type|Meas Type|S|OMOP generated|1970-01-01| 2099-12-31|

**Comment by dimshitc** [comment]
Should we add the same 'Condition Type' as we can derive ICD-O condition from Tumor Registry
and 'Observation Type' concepts as some source concepts can be mapped to Observation as well?

**Comment by mgurley** [comment]
@dimshitc Yes to 'Condition Type'.  That sounds like a good idea.

**Comment by mgurley** [comment]
Add this for all domains for the type_concept_id.

**Comment by mgurley** [comment]
This does not look like it has been applied to all domains beyond 'Episode' and 'Condition'.  I am needing it for 'Procedure'.

**Comment by dimshitc** [comment]
This inspiried me to start the conversation 
https://forums.ohdsi.org/t/type-concepts-consolidation/8025
Let the golden age happen!

**Comment by sratwani** [comment]
Team's decision is to put this on-hold. Issue is being tracked for the Development group once this vocabulary work is done.

**Comment by cgreich** [comment]
https://forums.ohdsi.org/t/concept-type-consolidation-please-take-a-look/8306

It's not "Tumor registry" but "Registry", but the fact that it is a tumor registry is obvious from the METADATA table and the content.

**Comment by sratwani** [comment]
@dimshitc @cgreich I checked out the forum discussion https://forums.ohdsi.org/t/type-concepts-consolidation/8025/7 and seems like folks and Christian are in agreement with the overall proposal of consolidating the type concepts. With that in mind is there anything else we need from the forum discussion before we can proceed with adding 'Registry' type concept to all domains? Seems like from @mgurley feedback, it was applied only to 'Episode' and 'Condition'.

**Comment by sratwani** [comment]
@dimshitc @mgurley Looks like this issue has been fixed. I see the 'Registry' Type Concept added. Okay to close this?
