### ISSUE TITLE
Representation of vital status and date of vital status from NAACCR

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#110]
Proposal: Observation period is derived from vital status: diagnosis date – start/ death date – end

**Comment by sratwani** [comment]
Per the discussion on 10/31, @rimusia will work on this as a modeling task. There were some discussions around whether we want to use NAACCR data (Death, survival date etc) to enhance our OMOP (observation end period etc). The group was leaning towards doing that as a secondary ETL if this enhancement was needed to obtain this additional information.

**Comment by mgurley** [comment]
I believe we should do this in the main NAACCR ETL.  Not a secondary ETL.  A little background on how NAACCR encodes last followup date and death date.  There are two relevant NAACCR fields
- DATE OF LAST CONTACT: http://datadictionary.naaccr.org/default.aspx?c=10#1750
- VITAL STATUS: http://datadictionary.naaccr.org/default.aspx?c=10#1760

If 'VITAL STATUS'=0, then the date in 'DATE OF LAST CONTACT' is the patient's death date.
If 'VITAL STATUS'=1, then the date in 'DATE OF LAST CONTACT' is last followup date that the patient was known to be alive.

I recommend the following:

If 'VITAL STATUS'=0, then the NAACCR ETL code should update the 'death_datetime' in the 'PERSON' table with the value in 'DATE OF LAST CONTACT'. if death_datetime is NULL.

If 'VITAL STATUS'=1, then the NAACCR ETL code should update for the person the 'observation_period_end_date' in the 'OBSERVATION_PERIOD' table if 'observation_period_end_date' is before the 'DATE OF LAST CONTACT'.

A couple of points:

- I believe we will add great complexity to NAACCR ETL process if we delegate this kind of important logic to live outside of the main NAACCR ETL.
-We committed to produciing more accurate results for the first milestone, [Rerun symposium plots with expanded ](https://github.com/OHDSI/OncologyWG/milestone/4).  This will help achieve  that goal.

**Comment by cgreich** [comment]
My $0.02: As you know, my affinity to the NAACCR is low, since I don't have the data, and neither have most data owners in the world. But still, support what you are doing. 

And yes, death should be dealt with according to OMOP standards. But last contact: Wouldn't that be a visit?

**Comment by mgurley** [comment]
@cgreich 

For last contact, I am OK with creating a visit, and was actually going to propose that possibly.   However, not sure it technically falls into that definition of visit.  These last contact dates are often dine via telephone calls from the tumor registry to the patient's home.  But if we think it can fit into VISIT_OCCURRENCE, I am all for it.  Many research/registry patients will have survival verified outside the formal healthcare setting,  so this is an issue that should be probably agreed upon by the community outside of Oncology.

> 
> > 
> The VISIT_OCCURRENCE table contains the spans of time a Person continuously receives medical services from one or more providers at a Care Site in a given setting within the health care system. Visits are classified into 4 settings: outpatient care, inpatient confinement, emergency room, and long-term care.

**Comment by cgreich** [comment]
I see. Makes sense.

**Comment by dimshitc** [comment]
@sratwani why is it moved to Done?

**Comment by mgurley** [comment]
@dimshitc 

There was no vocabulary work.  Just modelling work.  Remember, this is Vocabulary **and Modelling** Workgroup.  The workgroup made a modelling decision where and how these NAACCR data points would fit into the CDM.  This decision required no vocabulary additions.  Now there is a task for the Development Workgroup to implement the **modelling** decision.  Make sense?

**Comment by sratwani** [comment]
Closing as this has a Development issue .
