### ISSUE TITLE
Create a mapping table to be used for handling ambiguous ICDO site/histology combinations present in multiple schemas.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#113]

**Comment by sratwani** [comment]
Based on the 10/17 vocabulary call, Christian, Rimma and Dima need to scope the requirements out for this task. Awaiting their discussion before this task can be assigned.

**Comment by cgreich** [comment]
@mgurley or @dimshitc : Can you provide an example? I can't remember what this was.

**Comment by dimshitc** [comment]
It was decided that we need this kind of table:

icdo_site_histology | naaccr_item | naaccr_item_code | sex | csfactor25 | naaccr_item_omop_concept_id | naaccr_item_code_omop_concept_id
see #59 

So, I should make this for all schemas to be consistent, right?

I see 'csfactor25' here. What about '3926' -- Schema Discriminator 1 and '3927' --  Schema Discriminator 2 ?
they can be used as well
see
http://datadictionary.naaccr.org/default.aspx?c=10#3927
http://datadictionary.naaccr.org/default.aspx?c=10#3926

**Comment by mgurley** [comment]
@dimshitc  @cgreich 
Yes we need a column for every possible additional NAACCR item that is needed to disambiguate a site/histology/naaccr item/naaccr item code combination.   Here is a list of all the ambiguities at the NAACCR item level:

https://drive.google.com/file/d/1MeZi95W9_PCeXEoI2J8SzppeqfbkI6rm/view?usp=sharing

This list was created based on this SQL:

https://github.com/OHDSI/OncologyWG/blob/master/etl/support/debug_naaccr_item_ambiguites.sql

If you look at the first two rows of this spreadsheet you will see the following two schemas for the same ICDO site/histology/naaccr item combinations.

- Peritoneum (excluding Gastrointestinal Stromal Tumors and Peritoneum Female Genital M-8000-8576, 8590-8671, 8930-8934, 8940-9110 for females)
- Peritoneum for Females Only

So if you look and compare the following:
https://staging.seer.cancer.gov/tnm/schema/1.9/peritoneum/?breadcrumbs=(~schema_list~)

https://staging.seer.cancer.gov/tnm/schema/1.9/peritoneum/?breadcrumbs=(~schema_list~)

You will see that sex =1, 3-5, 9 is needed.  Maybe there is a more automated way to do this via the SEER API but I have not looked into that.  All in all there are only 13 schemas with ambiguous NAACCR items.  So it should not be that much work.  Someone needs to curate this list to discover the necessary possible other columns that need to be in the table.   Only the unique list of schemas from this file needs to be looked at.
  Here they are:
- Peritoneum (excluding Gastrointestinal Stromal Tumors and Peritoneum Female Genital M-8000-8576, 8590-8671, 8930-8934, 8940-9110 for females)
- Peritoneum for Females Only
- Retroperitoneum
- Malignant Melanoma of Skin, Vulva, Penis, Scrotum
- Malignant Melanoma of Upper Lip
- Malignant Melanoma of Lower Lip
- Malignant Melanoma of Other Lip
- Malignant Melanoma of Ciliary Body (excluding Iris)
- Malignant Melanoma of Iris (excluding Ciliary Body)
- Brain and Cerebral Meninges
- Hodgkin and Non-Hodgkin Lymphomas of All Sites (excluding Mycosis Fungoides and Sezary Disease)
- Other Parts of Central Nervous System
- Hematopoietic, Reticuloendothelial, Immunoproliferative, and Myeloproliferative Neoplasms

**Comment by sratwani** [comment]
Per the 10/31 call, Dima's testing of the query revealed that we end up with several Value concepts for same ICDO-naaccr_item-code combination because ICDO codes drive to different schemes. To avoid this Dima will take all ICDO to Schemes from CS algorithm and take ICDO codes missing from CS algorithm from EOD. This was there wont be anymore ambiguous code besides the 13. Next steps will be to (1) replace the vocabulary (2) Change the NAACCR ETL code to incorporate the table (Robert) (3) Have one NAACCR ETL code base and run it through SQLRender to be able to generate the different dialects.

**Comment by dimshitc** [comment]
1) vocabulary is updated.

**Comment by sratwani** [comment]
@mgurley @rtmill Since the vocabulary is now updated with the corrections, the next step is to change the NAACCR ETL code to incorporate the changes.

**Comment by sratwani** [comment]
@dimshitc Can this issue be closed. I have another [Issue 166](https://github.com/OHDSI/OncologyWG/issues/166) track the Development work.

**Comment by sratwani** [comment]
Vocabulary work is complete. Development effort is being tracked with [Issue 166](https://github.com/OHDSI/OncologyWG/issues/166)
