### ISSUE TITLE
Polish symposium analytical package.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#114]
Produce a fully functional standalone package the end-users can easily download and use to execute the plots that were used for the symposium along with being able to customize some aspects of the plot such as scale and labels since those can be thrown off by data variability
between institutions.

**Comment by patelm9** [comment]
Uploaded the latest version "oncoSurvivalPlotterV2" package to this repo. A few sub-issues:
-Run these scripts in a sandbox environment to see how they perform with test data
-Integrate the functions with the SQL output (Rimma's SQL script). We may be able to integrate the entire data pull in the package.
-Make the arguments for functions and ggplot2 and survival package more flexible for the end-user such as the scaling. Right now there are significant constraints.
-Debug and iterate

**Comment by chandryou** [comment]
Thank you @patelm9 
I and @neal1202 will take a look at it and figure out how to integrate SQL within this package. :)

**Comment by sratwani** [comment]
@patelm9 and @chandryou could either of you define what the definition of complete would be for this particular task? In other words, what needs to be done to complete this task.

**Comment by meerawhy** [comment]
To me, this means that it is a full functional standalone package the
end-users can easily download and use to execute the plots we used for the
symposium along with being able to customize some aspects of the plot such
as scale and labels since those can be thrown off by data variability
between institutions.

**Comment by sratwani** [comment]
@meerawhy Thanks for providing the completion criteria. Could you provide any update on this. Not sure if you plan to be on the Development call today.

**Comment by patelm9** [comment]
We need the original SQL script that was written to generate the data to input into this package. We can integrate it into the package itself. Then we can clean up the aesthetics of the package and it should be good to go from there.

**Comment by patelm9** [comment]
Update: found the SQL and just pushed it to the repo. I will integrate with the rest of the package in due time.

**Comment by mgurley** [comment]
@patelm9 

I had placed the SQL from the symposium here: https://github.com/OHDSI/OncologyWG/tree/master/analysis.

**Comment by patelm9** [comment]
@mgurley Thanks so much. Given that there aren't fires I need to put out otherwise, I'll be able to integrate the SQL into the package and give the newest version a test run.

**Comment by patelm9** [comment]
@vladrizescu might be able to help with this since he has been working on his ggplot2 skills!

**Comment by patelm9** [comment]
@mgurley @chandryou @sratwani 
I have not ever push a package as part of repo (only as a repo) so I pushed the newest iteration of the package that fully integrates the SQL queries written by @rimusia into the functions themselves. Inputs would simply be the connection details to the OMOP instance. 

https://github.com/patelm9/oncoPlot/tree/master
to install: devtools::install_github("patelm9/oncoPlot")

**Comment by sratwani** [comment]
@patelm9 @mgurley @chandryou what are the next steps here? Do we want to test out the polished analytical package before closing this issue?

**Comment by patelm9** [comment]
@mgurley @rtmill @ansi90 
Pushed the oncoPlot discussed in today's meeting to master.

**Comment by patelm9** [comment]
@mgurley @rtmill @sratwani Work has kept me away the last few weeks, but I am happy to report that our OMOP instance will be ready around the end of this month so I would be able to run the OncoPlot package to troubleshoot. Are there any updates in regards to the plot output from anyone else? @ansi90 I am also looping you in because of the schema argument that was required since not all tables will be in the same schema.

**Comment by patelm9** [comment]
@sratwani added the README. Also after installing package, running `?oncoPlot` in R would also pull up additional documentation on the packages. I want to stop here with the README and make appropriate changes in time for the deadline.

**Comment by patelm9** [comment]
@ansi90 would you be able to help finetune one of the plotting functions? I saw the beautiful plots that come out of OncoRegimenFinderV3 and we can really use your knowledge of ggplot to help with the histogram piece of the package.
