### ISSUE TITLE
Run Anastasios's OncoRegimenFinder finder script at multiple institutions. 

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#115]

**Comment by sratwani** [comment]
@mgurley @rtmill @ansi90 Robert will run the script 'OncoRegimenFinder' against Tufts data asset. We need other participants to run the package as well. Adding this to the Outreach/Research repo.

**Comment by sratwani** [comment]
Per the call on 10/23, Chan offered running the algorithm on their data. 
Michael (Northwestern data), Robert (TUFTS), Columbia are potential data partners that could run existing algorithm against their data.

**Comment by sratwani** [comment]
Per the call on 10/23, MSKCC is in the process of converting Medications data to OMOP (timeframe is 2 months), they should be able to run the algorithm and validate it against their data.

**Comment by sratwani** [comment]
@chandryou @ansi90  Chan, could you please provide a status on running the algorithm against your data. I believe Anastasios has provided you the instructions and steps to do the same.

**Comment by sratwani** [comment]
Below post has been submitted to solicit participation:

https://forums.ohdsi.org/t/oncology-wg-inviting-participants-with-ehr-data-to-run-the-oncoregimenfinder-script/8485

**Comment by sratwani** [comment]
Drug Regimen Algorithm has been executed on Northwestern, Tufts and Columbia.
