### ISSUE TITLE
Add concepts, domains and concept classes for EPISODE table.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#12]
**DOMAIN**

domain_id | domain_name | domain_concept_id
------------ | -------------|-------------|
Episode | Episode | ?

**VOCABULARY**

vocabulary_id | vocabulary_name |vocabulary_reference|vocabulary_version|vocabulary_concept_id
------------ | -------------|-------------|-------------|-------------
Episode | OMOP Episode |OMOP generated||?

**CONCEPT_CLASS** 

concept_class_id| concept_class_name | concept_class_concept_id
------------| ------------ | ------------
Disease Episode| Disease Episode|?
Treatment Episode| Treatment Episode | ?
Episode of Care | Episode of Care  | ?

**CONCEPT** 

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
?| Episode|Metadata|Domain|Domain||OMOP generated|1970-01-01|2099-12-31|
?| Disease Episode|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Treatment Episode|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Episode of Care Episode|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Disease First Occurrence|Episode|Episode|Disease Episode|S|OMOP generated|1970-01-01|2099-12-31|
?| Disease Recurrence|Episode|Episode|Disease Episode|S|OMOP generated|1970-01-01|2099-12-31|
?| Disease Remission|Episode|Episode|Disease Episode|S|OMOP generated|1970-01-01|2099-12-31|
?| Treatment Regimen|Episode|Episode|Treatment Episode|S|OMOP generated|1970-01-01|2099-12-31|
?| Treatment Cycle|Episode|Episode|Treatment Episode|S|OMOP generated|1970-01-01|2099-12-31|
?|Episode of Care|Episode|Episode|Episode of Care |S|OMOP generated|1970-01-01|2099-12-31|

**Comment by dimshitc** [comment]
Concept_class_id for the "Episode of Care" should be just "Episode of Care", does it make more sense?

I agree with the other things here.

**Comment by dimshitc** [comment]
The new "Episode" vocabulary will have OMOP_required = 'Y'
It means, you don't see it in the list of the vocabularies here http://athena.ohdsi.org/vocabulary/list
but it's included by default in any vocabulary bundle.
Are you OK with that?

**Comment by dimshitc** [comment]
added to the release. will be on Athena tonight
