### ISSUE TITLE
Write unit tests framework for NAACCR ETL code base.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#122]

**Comment by sratwani** [comment]
This task is complete. Michael presented the framework on 11/6. 
NAACCR ETL SQL can be found in the [link](https://github.com/OHDSI/OncologyWG/tree/master/etl) 
Link includes:
Ruby on Rails application used to setup a testing framework. 
Instructions on how to get it up and running.
Instructions on preparing the testing environment.
