### ISSUE TITLE
Determine modelling support for 'Response to treatment'.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#128]
- Progression
- Stable Disease
- Complete response

**Comment by mgurley** [comment]
Proposal: treatment modifier in the Measurement table or new Outcome table/domain.

**Comment by cgreich** [comment]
Let's close this and move the discussion to [144](https://github.com/OHDSI/OncologyWG/issues/144).

**Comment by sratwani** [comment]
This
