### ISSUE TITLE
Expand support for diagnosis modifiers. 

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#129]
Options:
- CAP checklists into vocabulary
- CAPS checklists and Nebraska
- Just new concepts describing CAP checklists.

Related to #9

**Comment by dimshitc** [comment]
We uploaded some eCC files into our environment.
@cgreich did you have a chance to look at CAP eCC September 2019 Agile Release?

**Comment by mgurley** [comment]
Duplicates #179, #7
