### ISSUE TITLE
Determine vocabulary support for genomic data.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#135]

**Comment by patelm9** [comment]
I also posted this in a Genomics subgroup:
> So far, I have identified the following vocabularies that are out there:
> -LOINC: for genomics test results HL7 FHIR uses US core LOINC with CLASSTYPE = 1
> -NCBI's Genetic Test Registry: for gap coverage for genomics concepts not covered by LOINC, HL7 defers to GTR
> -Human Genome nomenclature committee https://www.genenames.org/about/guidelines/
> -Human Genome Variation Society for Variant data: https://www.hgvs.org/
> -NCBI's dbSNP reference ids

**Comment by jeremywarner** [comment]
Hi Meera,

In the spirit of not re-inventing too many wheels, please have a look at this spreadsheet that I’ve assembled over the years (not sure if attachments go through to the listserv; if they do not, email me directly and I’ll send you a copy). Pertinent to genomics, there are 39+ terminologies with gene or gene alteration data, 29+ with protein or protein pathway data, and more. Note there’s a separate tab for nomenclatures, for example HGVS is a nomenclature whereas HGNC is a terminology.

I hope it is useful and if you see something missing let me know – I’m always looking to continue building this further!

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by patelm9** [comment]
Hey Jeremy,

This is amazing and exactly what I’m looking for! The attachment didn’t come through though. Could you send it over via email?

Meera Y. Patel, MD
Sr. Ontologist & Knowledge Representation Analyst
Division of Health Informatics | Knowledge Management & Innovation
Memorial Sloan Kettering Cancer Center
600 Third Avenue, 8th Floor, New York, NY 10017
(646) 888-8953 | PatelM9@mskcc.org

**Comment by chandryou** [comment]
We will investigate the information loss if we adopt [dbSNP](https://www.ncbi.nlm.nih.gov/snp/) (which has rsID), and [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/). You can read the articles about dbSNP [here](https://ncbiinsights.ncbi.nlm.nih.gov/2018/07/02/dbsnp-database-doubles-size-twice-13-months/).
There is the tool, [Mutalyzer](https://mutalyzer.nl/) converting dbSNP or rsID to HGVS notation.
