### ISSUE TITLE
Determine modelling support for genomic data.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#137]
See existing work here:
https://github.com/ABMI/GeneProfiler
https://forums.ohdsi.org/t/genomic-cdm-published-on-jmir-if-4-67/6447

**Comment by mgurley** [comment]
@chandryou @patelm9 

I think it would be useful at some point for Chan to walk through with the group each table in the
Entity Relationship Diagram of the Genomic CDM.  See here:

https://github.com/OHDSI/Genomic-CDM

I think describing the purpose of each table and the vocabularies tied to each field and the relationship between these new tables and existing CDM tables would be useful for the group to decide if the Genomic CDM  fits or exceeds the needs of our most pressing genomic use cases.  Plus possibly a description of how the data in these tables relates to the most common genomic results workflows. 

I am sure someone will say I am rushing to implementation but I think such a discussion will help everyone get bearing on the problem space in general.

**Comment by patelm9** [comment]
@mgurley Good point. I think this is a compelling question that really needs to be answered ASAP. @chandryou If we can get a good case for the reason why this extension is needed, that would be great. For example, why doesn't throwing this data in the observations/measurements table work for genomics data? Why do we need these extra tables?

@sratwani I think this is something that should be addressed in one of the upcoming meetings, if not the very next one if there is anyone that wants to take the reigns on this last minute for us to get a handle of why the existing CDM cannot handle genomics. I'm super swamped this week, but can try to see how much ground I can cover depending on how my Thursday looks. If not, we can focus on use cases and look into covering this in next week's meeting.
