### ISSUE TITLE
Add formal ontology properties to OROT.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#14]
We are planning on ingesting the Observational Research in Oncology Toolbox(OROT) into the OMOP vocabulary tables to provide a bridge between the low-level codes used in observational sources (EHRs/claims databases) to higher-level Procedure/Treatment concepts to be placed in the episode_object_concept_id column in the EPISODE table for 'Treatment Regimen '/'Treatment Cycle' episodes.  See here: https://seer.cancer.gov/oncologytoolbox/

We are asking NCI/SEER to add some formal ontology properties to OROT to facilitate the ongoing ingestion of OROT into the OMOP tables.

**Formal Ontology Properties**
- Use RxNorm codes as an anchor code for each entry.
- Use a stable identifier for classification concepts ('SEER*Rx Category', 'Major Drug Class' and 'Minor Drug Class').
- Timestamp the retirement of classification concepts (valid_start_date, valid_end_date).
- Distribute the OROT classification concepts in a separate file from the classification assertions.
- Timestamp the retirement of classification assertions.  For example, if a HCPCS/NDC/RxNorm code moves from 'Chemotherapy' to  'Immunotherapy'  in the SEER*Rx Category, please update the valid_end_date for the existing classification assertion and add another row with the new classification assertion with a valid_start_date.

**Comment by dimshitc** [comment]
Have anybody seen whether these categories have their internal codes?

**Comment by mgurley** [comment]
@dimshitc Yesterday OROT promised to provide these.

**Comment by mgurley** [comment]
We will reopen this possibly once we get the first distribution of OROT.
