### ISSUE TITLE
Determine vocabulary support for 'Response to Treatment'.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#144]

**Comment by cgreich** [comment]
Or is this Episode stuff?

**Comment by mgurley** [comment]
> Or is this Episode stuff?

Possibly, we need to decide how we are going to model response to treatment.  So might be in Episode or somewhere else.  See #128.  Which is not done yet.

**Comment by cgreich** [comment]
Hm. What exactly is response to treatment? I can see two ways:
- Episodes (Remission, stable disease, progressive disease)
- Details about the Condition, as determined by new diagnostic tests and procedures, resulting in more Condition and Measurement records after the treatment is completed. They would look exactly like the ones before the treatment.

The SNOMED codes above are very detailed Episode type Concepts. But I would be careful. They are very vague. What e.g. is "Poor response to treatment"? Give me the data.

**Comment by jeremywarner** [comment]
I would be careful about using any of those SNOMED terms; they are not typical for the parlance for response to cancer treatment. There was a thread about this some time ago on the OHDSI forum, but you might have a look at HemOnc.org’s Response to Treatment page: https://hemonc.org/wiki/Response_to_treatment. Needs work and is geared more towards the interval-based responses (progression free survival, etc) but does have the gist and also condition-specific endpoints which may be relevant to…specific conditions.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by mgurley** [comment]
@cgreich  @jeremywarner @rimusia 
Response evaluation criteria in solid tumors (RECIST) is a prominent example of a 'Response to Treatment' vocabulary that is used in clinical trials to measure the response of specific lesions to a treatment --largely based on dimensions measured on radiology exams.    Flatiron, as Jeremy alerted us to at our workshop, recently published on how tracking RECIST in the real word settings in infeasible.   The data just isn't there.  See here: https://flatiron.com/blog/is-the-cancer-better-or-worse/
 
Here is how RECIST is structured:

- Evaluation of target lesions
  - Complete response (CR): Disappearance of all target lesions
  - Partial response (PR): At least a 30% decrease in the sum of the LD of target lesions, taking as reference the baseline sum LD
  - Stable disease (SD): Neither sufficient shrinkage to qualify for PR nor sufficient increase to qualify for PD, taking as reference the smallest sum LD since the treatment started
   - Progressive disease (PD): At least a 20% increase in the sum of the LD of target lesions, taking as reference the smallest sum LD recorded since the treatment started or the appearance of one or more new lesions
- Evaluation of non-target lesions
   - Complete response (CR): Disappearance of all non-target lesions and normalization of tumor marker level
   - Incomplete response or stable disease (SD): Persistence of one or more non-target lesion(s) or/and maintenance of tumor marker level above the normal limits
   - Progressive disease (PD): Appearance of one or more new lesions and/or unequivocal progression of existing non-target lesions

We currently have 'Disease Episodes' and 'Treatment Episodes' in our model.  So a patient's trajectory might be so

- Disease Episode:  'Disease First Occurrence Episode' Adenocarcinoma of the Lung
- Treatment Episode:  Surgery
- Treatment Episode : Radiation Therapy    
- Treatment Episode : Drug Regimen
- Disease Episode : 'Disease Recurrence'

We need to decide if we want to model something beyond tracking 'Disease Episodes' and 'Treatment Episodes'  This something being 'Response to Treatment'.   In the above eample we could (not saying we should) add a 'Treatment Modifier' to hang off of the 'Drug Regimen' 'Treatment Episode ' that represents a 'Response to Treatment' of 'Progressive disease (PD)'.  Thus, any 'Treatment Episode' with a  'Progressive disease (PD)'.  'Treatment Modifier' maybe should be followed by a 'Disease Recurrence' 'Disease Episode'.  

I am inclined to think we should not try to model 'Response to Treatment' and just stick with 'Disease Episodes' and 'Treatment Episodes'.  Realizing that we need to further model 'Disease Episodes' .  See #123.

**Comment by jeremywarner** [comment]
Hi everyone,

The two major approaches to this problem are:


  1.  Anchor everything to a treatment episode, which itself defines the response to some degree. So if you’re in a first-line metastatic treatment episode, as long as you’re in it, the presumption that you have stable disease or better, or at least a clinical benefit, is valid. Once you transition to a second-line metastatic treatment episode, the presumption is that you’ve progressed and/or stopped the first treatment for toxicity.
  2.  Break the cancer journey into discretized progression/response events, anchored to specific dates. This is the PRISSMM approach, and allows you at the end to reconstruct the course of the disease without needing to have treatment episodes.

Probably a hybrid of both is the best answer, but choosing one or the other for a first effort should be sufficient!

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by cgreich** [comment]
@jeremywarner: 

This makes a lot of sense. So, all we would have to do is to use some heuristic, or some probabilistic method once we have it, and decide when the disease toggles from getting better (progressive, treatment discontinued) to turning worse (new treatment, remission). In fact, stable disease becomes really the absence of either of the two. 

From an analytic perspective, this is clean. Not sure what the community will say if we did that. Do you?

**Comment by jeremywarner** [comment]
This is essentially what the PRISSMM model is doing. Which community were you referring to? Various communities are piloting the PRISSMM model, including NCI SEER.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by cgreich** [comment]
Well, the oncology community. People who think there are half a dozen states of the disease.

**Comment by sratwani** [comment]
Vocabulary work complete with the inclusion of Episodes.
