### ISSUE TITLE
Work with CAP to incorporate/sync their vocabularies into OMOP.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#154]

**Comment by sratwani** [comment]
Based on the 10/22 Leadership Subgroup call, a decision was made to reach out to CAP and Campbells (Nebraska Lexicon), share our proposal with them (based on our evaluation of Nebraska Lexicon) to expedite their mapping efforts and formalize our relationships.

**Comment by sratwani** [comment]
Based on the 10/22 Leadership Subgroup call, a decision was made to reach out to CAP and Campbells (Nebraska Lexicon), share our proposal with them (based on our evaluation of Nebraska Lexicon) to expedite their mapping efforts and formalize our relationships.

**Comment by sratwani** [comment]
@dimshitc @cgreich Gentlemen, Can we close this? Isn't this complete?
