### ISSUE TITLE
Work with OROT to incorporate/sync their vocabularies into OMOP.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#156]

**Comment by cgreich** [comment]
Not sure what Michael changed in the title, but do we have OROT loaded already, @dimshitc?

**Comment by mgurley** [comment]
No OROT is not yet in the OMOP vocabulary.  They have only provided draft versions of their surgery and radiation therapy compendiums mapping EHR codes to NAACCR treatment variables.  So this task would involve nudging them to get final versions, so we can finish the ingestion.

**Comment by cgreich** [comment]
I meant is it already loaded into the vocab server, so we can slice and dice it. Whatever is there today. Also, didn't they already have the drug mappings as well?

**Comment by mgurley** [comment]
@cgreich 

I don't think the draft version of OROT is in the vocab server yet.  @dimshitc can let us know.  Regarding drug mappings, Hemonc.org is hopefully going to include in a future release all of the OROT drug mappings from NDC/HCPCS codes to NAACCR SEERRx drug categories that correspond to NAACCR drug treatments variables.  Need to ping @jeremywarner about that.  Thus the idea is that we will only use OROT for surgery and radiation therapy.
