### ISSUE TITLE
Determine possible expanded use cases for the rerun of the symposium plots.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#159]

**Comment by sratwani** [comment]
Christian and Andrew invited Chan, Sergio, Paul and Young Ji to bring their important use cases to develop a repository of uses cases we can execute against the extended Oncology CDM.

**Comment by chandryou** [comment]
Here is our accessible data list

|Database ID|Country|Type|Size|Year|Explanation|Conversion status| Contact|
|:---|:---|:---|:---|:---|:---|:---|:---|
|HIRA-Cancer|KOR|Nationwide claim| | |Whole national claim database|Completed, CDM v5.3 |@neal1202|
|Cancer Registry Sample|KOR|Cancer registry| | |10% sampled cancer registry of Korea|Data access applied |@neal1202|

**Comment by sratwani** [comment]
Per Leadership discussion on 12/16, Andrew will send the list to Shilpa. This issue can be closed.

**Comment by sratwani** [comment]
Closing per Christian's comment on 12/16 on not needing to solicit any more Use Cases.
