### ISSUE TITLE
CD2H OHDSI oncology WG collaboration

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#161]
CD2H is the 'National Center for Data to Health' initiative. Through the CD2H program, standardized approaches and best practices are being developed, including algorithms and other specialized tools, to address operational and institutional barriers to sharing data. Andrew has made the initial connection with Christopher Chute <chute@jhu.edu> and has invited them to attend our vocabulary subgroup calls or offered us up to do a presentation for the CD2H group.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
