### ISSUE TITLE
Solicit development of oncology drug regimen derivation algorithms.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#164]
@ansi90, @chandryou and @jeremywarner  have all created algorithms to derive oncology drug regimens from observational data.  We would like all of these participants and more to join in an "Oncology Drug Regimen Extraction Challenge".  Find other participants.

**Comment by sratwani** [comment]
There is documentation on how to run the scripts. @ansi90 will document steps to test the algorithm.

**Comment by sratwani** [comment]
@ansi90 in the process of soliciting development of oncology drug regimen from the community, is there anything specific that we need to include in our request so we gain access to the right kind of audience and data.

**Comment by sratwani** [comment]
[Forum Post](https://forums.ohdsi.org/t/inviting-participation-in-the-creation-of-the-oncology-drug-regimen-algorithm/8538) has been submitted to solicit participation.
