### ISSUE TITLE
Accessible data list

### ISSUE THREAD

**Issue by chandryou** [OHDSI/OncologyWG#165]
At the first research subgroup meeting, we agreed to identify accessible database and uses cases. 

I'm not sure this issue is good repository to collect this list, but we can start here. Then we can clean this up. 

So could you please list your accessible oncology data. 

Note that you can vote on each post. 

Please summarize your accessible data according to the table below. 
```
|Database ID|Country|Type|Size|Year|Explanation|Conversion status| Contact|
|:---|:---|:---|:---|:---|:---|:---|:---|
| | | | | | | | |
```

**Comment by chandryou** [comment]
|Database ID|Country|Type|Size|Year|Explanation|Conversion status| Contact|
|:---|:---|:---|:---|:---|:---|:---|:---|
|HIRA-Cancer|KOR|Nationwide claim| | |Whole national claim database|Completed, CDM v5.3 |@neal1202|
|Cancer Registry Sample|KOR|Cancer registry| | |10% sampled cancer registry of Korea|Data access applied |@neal1202|

**Comment by sratwani** [comment]
Thanks @chandryou. I'm currently putting together a list of the data assets and use cases we already have in our backlog and will add it to the OHDSI wiki shortly. This is a good spot to collect others. I'll share with the rest of the subgroup members.

**Comment by sratwani** [comment]
Closing this as this is being tracked in #159
