### ISSUE TITLE
Centralize existing standard genomic vocabularies

### ISSUE THREAD

**Issue by meerapatelmd** [OHDSI/OncologyWG#173]
A genomics/ directory with vocabulary/ has been created to start the information gathering process. All standard and source vocabularies should be posted to vocabulary/ and a comment with a description of what has been posted should be submitted to this issue for review as a team at subsequent meetings.

**Comment by denyskaduk** [comment]
Hello! Do you mean to use loinc as 'existing standard genomic vocabularies':  
loincnumber | longcommonname | partnumber | partname | parttypename
-- | -- | -- | -- | --
21640-8 | BRCA2 gene c.6174delT [Presence] in Blood or Tissue by Molecular genetics method | LP288106-0 | BRCA2 gene | GENE
79208-5 | BRCA2 gene mutation analysis limited to known familial mutations in Blood or Tissue by Molecular genetics method | LP288106-0 | BRCA2 gene | GENE
38530-2 | BRCA2 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal | LP288106-0 | BRCA2 gene | GENE
38531-0 | BRCA2 gene mutations tested for in Blood or Tissue by Molecular genetics method Nominal | LP288106-0 | BRCA2 gene | GENE

**Comment by denyskaduk** [comment]
Hello! Do you mean to use LOINC as 'existing standard genomic vocabularies'? As I know LOINC keep some gene measurements with gene as attribute, for example: 


loincnumber | longcommonname | partnumber | partname | parttypename
-- | -- | -- | -- | --
21640-8 | BRCA2 gene c.6174delT [Presence] in Blood or Tissue by Molecular genetics method | LP288106-0 | BRCA2 gene | GENE
79208-5 | BRCA2 gene mutation analysis limited to known familial mutations in Blood or Tissue by Molecular genetics method | LP288106-0 | BRCA2 gene | GENE
38530-2 | BRCA2 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal | LP288106-0 | BRCA2 gene | GENE
38531-0 | BRCA2 gene mutations tested for in Blood or Tissue by Molecular genetics method Nominal | LP288106-0 | BRCA2 gene | GENE

**Comment by patelm9** [comment]
@denyskaduk Yes, this is a good example! Also, we need to gather the standard vocabularies that were used in the paper @chandryou had discussed last week.

**Comment by patelm9** [comment]
**So far, I have identified the following vocabularies that are out there:**
-LOINC: for genomics test results HL7 FHIR uses US core LOINC with CLASSTYPE = 1
-NCBI's Genetic Test Registry: for gap coverage for genomics concepts not covered by LOINC, HL7 defers to GTR
-Human Genome nomenclature committee https://www.genenames.org/about/guidelines/
-Human Genome Variation Society for Variant data: https://www.hgvs.org/
-NCBI's dbSNP reference ids

**Comment by patelm9** [comment]
@jeremywarner shared with me that he has been centralizing terminologies over time. I will post to the repo to discuss its application as soon as I receive a copy.

**Comment by lucid0921** [comment]
> **So far, I have identified the following vocabularies that are out there:**
> -LOINC: for genomics test results HL7 FHIR uses US core LOINC with CLASSTYPE = 1
> -NCBI's Genetic Test Registry: for gap coverage for genomics concepts not covered by LOINC, HL7 defers to GTR
> -Human Genome nomenclature committee https://www.genenames.org/about/guidelines/
> -Human Genome Variation Society for Variant data: https://www.hgvs.org/
> -NCBI's dbSNP reference ids

HGVS rule is explained in this page(http://varnomen.hgvs.org/) and we can reference it when doing ETL variant into Genomic-CDM.

**Comment by lucid0921** [comment]
Some controlled vocabulary system can be used in genomic-CDM but in ATHENA there is in short of concept_ids to cover them.

I share [a pdf file](https://drive.google.com/open?id=1bB2e_Q2wzcv6xxMb8mOin2fuPCbCzdJF) that summary of vocabulary we need. The contents had presented briefly in a face-to-face meeting at the 2018 OHDSI Symposium in Washington.

![image](https://user-images.githubusercontent.com/34934336/68945764-826fc880-07f4-11ea-913b-caa97e1a9302.png)
