### ISSUE TITLE
Add missing 'ICDO to Schema' relationships

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#176]
I noticed in our data there are a few ICDO3 condition concepts that are frequent in the data but do not have a mapping to a schema in the vocabularies. Can these relationships be added? 

condition_concept_code | condition_concept_id | schema_concept_code | schema_concept_id
-- | -- | -- | --
9732/3-C42.1 | 44500967 | plasma_cell_myeloma | 35909779
9823/3-C42.1 | 44504688 | lymphoma_cll_sll | 35909729

**Comment by sratwani** [comment]
Per Dima and discussion in the 12/26 vocabulary meeting. This issues is complete and can be closed.
