### ISSUE TITLE
Rimma's Housekeeping Tasks

### ISSUE THREAD

**Issue by rimusia** [OHDSI/OncologyWG#18]

**Comment by rimusia** [comment]
Change link on the main CDM WG page
Write a mission statement
Create presentations/publications section and transfer from the old one
Upload the contact list
Add meeting information

**Comment by cgreich** [comment]
Not the main CDM WG page, but the Oncology WG page. The way to link to the CDM page is through Issues on Githubs.

**Comment by rimusia** [comment]
There is a link at the main CDM WG page to subgroups. Michael and I are changing the Onco WG page to the GitHub wiki.
