### ISSUE TITLE
Use Case and Data source repository building

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#181]
This issue is used to intake information from participants that wish to contribute their data for the Oncology CDM Extension efforts so use cases/research studies can be run against the data. Please provide the below information if you wish to contribute.

1) Site Name
2) Registry [e.g NAACCR, Free text, ….]
3) EHR [e.g General purpose, Oncology-specific]
4) Trial [e.g STDM, AdAM, EPIC-BEACON, Other]
5) Desc of Patient Population [Free text]
6) Depth of data

**Comment by patelm9** [comment]
Use Cases from the Genomics Subgroup can be found in this issue: https://github.com/OHDSI/OncologyWG/issues/172#issue-509619553
