### ISSUE TITLE
build relationships 'ICDO to schema' for 'NULL-XXX' scheme

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/OncologyWG#193]
after we done #67 
we have to add  'NULL-XXX'  to NAACCR Schema

**Comment by denyskaduk** [comment]
If we look only at site, we see that one 'ICDO Condition' can have multiple schemas. For example: C50.9 - 'Malignant neoplasm of breast of unspecified site' can have 5 schemas:

schema_id | relationship | concept_code | concept_name
-- | -- | -- | --
breast | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS
myeloma_plasma_cell_disorder | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS
kaposi_sarcoma | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS
heme_retic | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS
lymphoma | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS


We have to choose, what to do in this case. All 'NULL-XXX' conditions have 5 or more schemas. If we leave these relations as is, better don't keep it all. We tend to keep only schema which is site identification, as we do with 'Neoplasm, uncertain whether benign or malignant', for example '8000/1-C50.9':

schema_id | relationship | concept_code | concept_name
-- | -- | -- | --
breast | Schema to ICDO | 8000/1-C50.9 | Neoplasm, uncertain whether benign or malignant of breast 

Those 'NULL-C50.9' will have such relationship: 

schema_id | relationship | concept_code | concept_name
-- | -- | -- | --
breast | Schema to ICDO | NULL-C50.9 | Neoplasm defined only by topography: Breast, NOS

**Comment by dimshitc** [comment]
@mgurley @cgreich @rimusia 
please confirm the logic of schema definition for NULL-XXX concepts.
We link them to organ-specific schema only.
i.e. 
NULL-C50.9 -> breast
(Technically NULL can mean Lymphoma as well, but we're omitting this).

**Comment by rtmill** [comment]
As discussed today on call, this is no longer needed.
