### ISSUE TITLE
TCGA genomic and clinical data 'Multiple Myeloma (Broad, Cancer Cell 2014)'

### ISSUE THREAD

**Issue by lucid0921** [OHDSI/OncologyWG#194]
Hi, after our meeting last week, I downloaded the TCGA genomic and clinical data of patients with Multiple Myeloma (Broad, Cancer Cell 2014). 

The data have whole-exome or whole-genome sequencing of 203 multiple myeloma paired tumor/normal sample pairs.

I re-stored some txt files to xlsx files for easy review.

[Share folder of downloaded data](https://drive.google.com/open?id=1tzTxaQg4UhDebTYPxII3Q-mEwje5qlDf)

[Related paper of the dataset](https://www.ncbi.nlm.nih.gov/pubmed/24434212)

[cBioportal page of the dataset](http://www.cbioportal.org/study/summary?id=mm_broad)

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
