### ISSUE TITLE
mCODE review

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#197]

**Comment by patelm9** [comment]
@rimusia @sratwani 
I reached out to Andre to see if we would be able to schedule a presentation on the genomics piece of mCode at an upcoming Genomics Subgroup meeting.

**Comment by sratwani** [comment]
Besides Genomic we are interested in their choice of the vocabulary. We may plug into those vocabularies when we map NAACCR to the standard in our choice of the standard.
