### ISSUE TITLE
Translate NAACCR ETL SQL to different dialects

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#199]
Assigning it to Michael and Robert for now until Dave Sonnet gets added to the Git. Dave has volunteered to work on this task.

**Comment by mgurley** [comment]
Consider using 

- https://github.com/OHDSI/SqlRender
- https://github.com/dmtolpeko/sqlines

**Comment by cgreich** [comment]
> Consider using:

Don't just consider. This is the way we ought to do it. Not that difficult, really.
