### ISSUE TITLE
Review breast cancer use case from MSKCC

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#202]

**Comment by lucid0921** [comment]
In TCGA, [many NGS datasets of patients with breast cancer](http://www.cbioportal.org/) were uploaded.
If the use case is set up in a working group, we'll download some of them and convert to genomic CDM for study.

![image](https://user-images.githubusercontent.com/34934336/68946249-d4fdb480-07f5-11ea-8124-4db478d89445.png)

**Comment by lucid0921** [comment]
I reviewed Targeted sequencing data of patients with Breast cancer in TCGA.  

![image](https://user-images.githubusercontent.com/34934336/69408377-120ffc80-0d4a-11ea-8187-007089fe86e2.png)
Related paper: https://www.ncbi.nlm.nih.gov/pubmed/30205045
Quick summary page: http://www.cbioportal.org/study/summary?id=breast_msk_2018

| # | File name | nrow | ncol | description |
|:---:|:---:|:---:|:---:|:---|
| 1 | clinical_patient | 1,756 | 21 |  Patient ID and clinical information about breast cancer (stage, laterality, vital_status etc.) |
| 2 | clinical_sample | 1,918 | 33 | Pathological information of   specimen (primary, metastasis, origin tissue, stage_at_diagnosis, tumor_grade etc.) |
| 3 | mutations_mskcc | 3,463 | 45 | Variant information such as SNP, Insertion, Deletion |
| 4 | mutations_extended | 6,130 | 45 | Extended documents prior to make "mutation_mskcc" file by filtering |
| 5 | fusions | 474 | 10 | The situation of the fusion between the two genes is described by a free-text. |
| 6 | CNV | 474 | 1,919 | The copy number of CNV variants occurred in 474 genes and 1,918 targets(?) are described as -1, 0, 2.5, etc. |

[Files downloaded from TCGA.](https://drive.google.com/open?id=1m2GoDs6Taudwu6VihH6z3IfEk-pxBOLF)

![image](https://user-images.githubusercontent.com/34934336/69410552-a2504080-0d4e-11ea-85c0-f6f1c7079fd4.png)

[Sample data of this dataset were converted into Genomic-CDM.](https://drive.google.com/open?id=1imC1Y3iMp92qxc30fuhyZ0-3zvRFCLl9)

![image](https://user-images.githubusercontent.com/34934336/69410767-083cc800-0d4f-11ea-879f-511f695e6770.png)

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
