### ISSUE TITLE
Fix NAACCR ETL for 'unknown histology'

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#205]
This task is to make sure the ETL works with the ICD-O concept created for 'unknown histology' [issue # 67](https://github.com/OHDSI/OncologyWG/issues/67).

**Comment by rtmill** [comment]
As discussed in vocabulary subgroup meeting, this is no longer needed. The ETL already incorporates schema-independent variables.

**Comment by mgurley** [comment]
We need to add a unit test to make sure this is covered.
