### ISSUE TITLE
Add Episode Type concepts.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#21]
**VOCABULARY**

vocabulary_id | vocabulary_name |vocabulary_reference|vocabulary_version|vocabulary_concept_id
------------ | -------------|-------------|-------------|-------------
Episode Tpe | OMOP Episode Type |OMOP generated||?

**CONCEPT_CLASS** 

concept_class_id| concept_class_name | concept_class_concept_id
------------| ------------ | ------------
Episode Type|Episode Type|?

**CONCEPT** 

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
?| Episode Type|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Episode Type|Metadata|Vocabulary|Vocabulary||OMOP generated|1970-01-01|2099-12-31|
?| Pre-made treatment abstraction with pre-made clinical events connections.|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Pre-made treatment abstraction with algorithmically derived clinical events connections.|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Pre-made treatment abstraction with no clinical events connections.|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Algorithmically derived treatment abstraction and clinical event connections.|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|

**Comment by cgreich** [comment]
What are "Clinical event connections"?

**Comment by mgurley** [comment]
@cgreich Elinical event connections are entries in EPISODE_EVENT.  Definitely open to better verbiage.

**Comment by cgreich** [comment]
Why do we have to declare they have linked events? Isn't it self-evident when you join the tables?

**Comment by mgurley** [comment]
@cgreich Yes, you are correct.  Joining will tell you if the connections exist, but not how the connections were made: taken from the source system or algorithmically derived or not present at all because neither.  We have discussed being able to track the provenance of data being placed in the EPISODE/EPISODSE_EVENT tables and this is what these entries are trying to convey.

**Comment by cgreich** [comment]
Yeah. That's overloading the Type concepts. Plus, it's not clear to me why you will gain. If you want to know if something has events just look into the table.

**Comment by mgurley** [comment]
@cgreich It's not about presence or absence.  It's about provenance of presence.  We want to know if the abstraction/connection was present in the source system or algorithmically derived and the nature of the source system: EHR, Tumor Registry or Claims.  I will drop reference to connections.  If we want to track whether an entry in EPISODE_EVENT was present in the source system or algorithmically derived, we can add an episode_event_type column to EPISODE_EVENT.  Anyways, let me know if you like this version:

**VOCABULARY**

vocabulary_id | vocabulary_name |vocabulary_reference|vocabulary_version|vocabulary_concept_id
------------ | -------------|-------------|-------------|-------------
Episode Type | OMOP Episode Type |OMOP generated||?


**CONCEPT_CLASS** 

concept_class_id| concept_class_name | concept_class_concept_id
------------| ------------ | ------------
Episode Type|Episode Type|?


**CONCEPT** 

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
?| Episode Type|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Episode Type|Metadata|Vocabulary|Vocabulary||OMOP generated|1970-01-01|2099-12-31|
?| EHR|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Algorithmically derived from EHR |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Tumor Registry|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Claims|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Algorithmically derived from Claims |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|

**Comment by cgreich** [comment]
Got it. Makes sense. 

Couple of editorial corrections:

EHR -> Episode defined in EHR
Algorithmically derived from EHR -> Episode algorithmically derived from EHR
Tumor registry -> Episode derived from registry
Claims -> Episode derived from claim
Algorithmically derived from Claims - Episode algorithmically derived from claim

**Comment by mgurley** [comment]
@cgreich  Agreed.  Final version:

**VOCABULARY**

vocabulary_id | vocabulary_name |vocabulary_reference|vocabulary_version|vocabulary_concept_id
------------ | -------------|-------------|-------------|-------------
Episode Type | OMOP Episode Type |OMOP generated||?


**CONCEPT_CLASS** 

concept_class_id| concept_class_name | concept_class_concept_id
------------| ------------ | ------------
Episode Type|Episode Type|?


**CONCEPT** 

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
?| Episode Type|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Episode Type|Metadata|Vocabulary|Vocabulary||OMOP generated|1970-01-01|2099-12-31|
?| Episode defined in EHR|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?| Episode algorithmically derived from EHR |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Episode derived from registry|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?| Episode derived from claim|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Episode algorithmically derived from claim |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|

**Comment by dimshitc** [comment]
So, @cgreich ,
is this a final version?

**Comment by cgreich** [comment]
Probably: "Episode defined in EHR" -> "Episode derived in EHR", since they are all derived.

**Comment by dimshitc** [comment]
No, it looks like different things:

"Episode **defined** in EHR" - when it's mentioned exactly in EHR
Episode algorithmically **derived** from EHR - when we derived it.

Well, using this logic, we might change 'Episode **derived** from claim' to 'Episode **defined** in claim', and 'Episode derived from registry' to 'Episode **defined** in registry' as well.

Thoughts?

**Comment by dimshitc** [comment]
Nobody answers, so I can make a decision here:
I like the version in the last table (with "defined in EHR" but derived from other places)

**Comment by mgurley** [comment]
Yes, treatment abstractions can actually be 'defined' in the EHR and not derived .  I have two use cases of this at NU.  Never seen it done elsewhere.  I agree with you (and myself).

**Comment by mgurley** [comment]
@cgreich @dimshitc  Ok, really the final version:

**VOCABULARY**

vocabulary_id | vocabulary_name |vocabulary_reference|vocabulary_version|vocabulary_concept_id
------------ | -------------|-------------|-------------|-------------
Episode Type | OMOP Episode Type |OMOP generated||?


**CONCEPT_CLASS** 

concept_class_id| concept_class_name | concept_class_concept_id
------------| ------------ | ------------
Episode Type|Episode Type|?


**CONCEPT** 

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
?| Episode Type|Metadata|Concept Class|Concept Class||OMOP generated|1970-01-01|2099-12-31|
?| Episode Type|Metadata|Vocabulary|Vocabulary||OMOP generated|1970-01-01|2099-12-31|
?| Episode defined in EHR|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?| Episode algorithmically derived from EHR |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Episode defined in registry|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?| Episode defined in claim|Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|
?|Episode algorithmically derived from claim |Type Concept|Episode Type|Episode Type|S|OMOP generated|1970-01-01|2099-12-31|

**Comment by cgreich** [comment]
You really are a true OMOP vocabularist, @mgurley! :)

Don't think there are Episodes defined in a claim, are there?

**Comment by mgurley** [comment]
@cgreich 
High compliments indeed!
Yes, I would doubt there ever would be episodes defined in a claims database.  I was being pedantic.  Fine by me to remove that one.

**Comment by mgurley** [comment]
This has been completed.
