### ISSUE TITLE
The collapsing of the NAACCR schemas needs to be validated.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#220]
While writing unit tests for the NAACCR ETL, one of the examples I chose to try to validate the insertion of diagnosis modifiers into the MEASUREMENT table revealed that the ICDO combination of '8070/2-C00.3' has been placed in the 'lip_upper' schema.  This makes it impossible to map NAACCR item number 772 'EOD Primary Tumor' because only the 'lip' schema has been pre-coordinated with NAACCR item number 772.

But it appears that ICDO combination '8070/2-C00.3' should be able to populate NAACCR item number 772.  See here:

https://staging.seer.cancer.gov/eod_public/schema/1.7/lip/?breadcrumbs=(~schema_list~)

My suspicion is that this not the only instance where this kind of issue exists due to the nature of how we collapsed the NAACCR schemas.  Is there a description of the logic of how we collapsed the NAACCR schemas?  Also, has #138 been completed, so that we can take a look at the logic?

We need to come up with an ingestion strategy that provides full coverage and can be easily explained to the external community to provide assurance that the parts of NAACCR that we are supporting are fully valid.

**Comment by dimshitc** [comment]
@denyskaduk check whether is it fixed in stage environment?

**Comment by sratwani** [comment]
@dimshitc Based on the Vocabulary call on 12/26, you are responsible for documenting the issue and also the approach you will be taking to resolve the issue.

**Comment by sratwani** [comment]
Per discussion on 12/26 > Need technical documentation on the issue and approach to resolve the issue. **Direction 1** - Christian’s suggestion - Create every ICO combination and pre-coordinate with viable values. **Direction 2** - Instead of #1 do what was done in the previous version where combination was related to both schemas then it should end up with same variable. Dima to try out both the above solutions to evaluate the results and approach.

**Comment by sratwani** [comment]
Per discussion on 1/2 -> Further assessment of this issue at NU and Tufts reveled minimal impacts. The plan is for MSK to run the query against their OMOP data to further assess the impact. If the impact remains low then any modeling changes can be delayed for a while.
