### ISSUE TITLE
Comprehensively fix missing leading zeros in the concept_codes for NAACCR values.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#234]
There is still a consistent problem of missing leading zeros in the concept_code column of NAACCR values:

For example, compare
http://datadictionary.naaccr.org/default.aspx?c=10#1504
https://api.seer.cancer.gov/rest/naaccr/latest/item/1504
http://athena.ohdsi.org/search-terms/terms/35918869

http://datadictionary.naaccr.org/default.aspx?c=10#1506
https://api.seer.cancer.gov/rest/naaccr/latest/item/1506
http://athena.ohdsi.org/search-terms/terms/35918276

This issue was partially addressed in #60, but it seems that there are still problems.  Can we do a systematic re-pull of the NAACCR data dictionary via the SEER API to fix this problem accross the board?

**Comment by sratwani** [comment]
@mgurley Looks like this issue has been fixed. I checked the above examples and the NAACCR Data Dictionary and Athena seem to be in sync. Can you confirm please.
