### ISSUE TITLE
Sharing ETL Code of Genomic-CDM

### ISSUE THREAD

**Issue by lucid0921** [OHDSI/OncologyWG#244]
I'm sharing the ETL code that converting a public TCGA-LUAD NGS data into the Genomic-CDM.
In the repository, there are variations and clinical files so that you can actually run.

https://github.com/ABMI/GCDM_ETL

![image](https://user-images.githubusercontent.com/34934336/72331253-37dad180-36fb-11ea-9fd7-0e56dd47279d.png)

**Comment by sratwani** [comment]
@lucid0921 Is this ETL code updated for the latest version of the G-CDM that we landed on? Essentially, using the Measurement table?

**Comment by lucid0921** [comment]
The uploaded code is for the G-CDM of the original version, not for the version using Measurement table only.

**Comment by mgurley** [comment]
Outside our control.
