### ISSUE TITLE
Proposal for Ingestion of NAACCR into OMOP Vocabulary - Diagnostic Modifiers

### ISSUE THREAD

**Issue by rimusia** [OHDSI/OncologyWG#25]
[NAACCR Ingestion into OMOP Vocabulary - Diagnostic Modifiers.docx](https://github.com/OHDSI/OncologyWG/blob/master/documentation/NAACCR.Ingestion.into.OMOP.Vocabulary.-.Diagnostic.Modifiers.docx)

**Comment by mgurley** [comment]
This is completed.  Needs to be vetted and beta tested.
