### ISSUE TITLE
SNOMED - OHDSI Vocabulary Workshop

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#252]
From Monica Harry <mha@snomed.org> 

Thank you for putting this list together, all very relevant to our cause. I will discuss with Jim to see if there is anything we want to add. As a starter, this will certainly give us as you say, plenty to discuss. 

With regard to the points below from your list, we are actively working on these at the moment so will be able to provide updates: 
 
-       Building a device hierarchy starting with Implants
-          Cancer in SNOMED, relationship to ICD-O-3, Nebraska lexicon, tumor attributes

I am going to go ahead and book a meeting room on April 2nd in London and will furnish details when I have them.

---------------------------------------------------------

From Christian

 
At the Unicom meeting, Monica, Jane and I discussed how we can take our long history of lose interactions about content issues to the next level, and came up with the idea of a workshop. We would sit down and go through all the ideas/issues/complaints/queries/confusions etc. We also want to get away from the notion that SNOMED should somehow have everything already perfect and done, and instead figure out a way how we can help each other. To help with that, some of us went to SNOMED school and already have some better insight into how SNOMED operates. But you guys probably have little insight into how we do things and why. And there are many subjects that have been floating for a while:
 
-          Mapping of ICD to SNOMED (not the other way around), typical issues, potential solutions
-          Building a procedure hierarchy with all the different local procedure coding schemes
-          Building a device hierarchy
-          Roles of drugs in SNOMED or outside, in particular dm+d, the Australian drugs, etc.
-          Relationship between SNOMED and LOINC
-          Cancer in SNOMED, relationship to ICD-O-3, Nebraska lexicon, tumor attributes
-          Genomic markers
-          General issues such as duplicates, life cycle rules, concepts without “social life” (relationships or hierarchy).

**Comment by sratwani** [comment]
Complete.

**Comment by dimshitc** [comment]
Before closing this task should we post some meeting Notes regarding the Oncology domain?
