### ISSUE TITLE
How should we handle long CONCEPT.concept_code entries that exceed 50 characters coming from NAACCR?

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#27]

**Comment by cgreich** [comment]
Can you show us?

**Comment by mgurley** [comment]
@cgreich Our tentative hope is that this will not be an issue, but we need the ingestion script to be completed to measure the longest length.  Dmitry's first cut indicated it will not be a problem.

**Comment by mgurley** [comment]
First version of NAACCR was ingested into the OMOP vocabulary, so any issues should be submitted.
