### ISSUE TITLE
Finalize Bladder Cancer Study

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#279]

**Comment by sratwani** [comment]
Remaining tasks:
a.	QC -> results; modify analytical package etc
b.	Desc comorbidities the way the community describes is
c.	Desc OS - Overall Survival, PFS (waiting on the derivation algorithm)
d.	Treatment -> needs QC and enhancements; Treatment Patters etc
e.	Run package against NWU and others

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
