### ISSUE TITLE
Phenotype definition for each organ

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#281]
To manage the issues with the SNOMED ICDO hierarchy, it was decided that in the short term, we will let them live in parallel and use the OR clause in Cohort Definitions to include all relevant codes until it's either fixed by SNOMED or addressed by the OHDSI community. It was also decided to document these recommendations for each Organ so anyone creating Cohort Definitions could use this as a guideline.

**Comment by aedin** [comment]
Given single cell data will be ported into clinical records in future, it is worth considering supporting a more extensive tissue/organ ontology (or is that possible).  https://www.ebi.ac.uk/ols/ontologies/bto

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
