### ISSUE TITLE
Genomic-CDM specifications question on latest model

### ISSUE THREAD

**Issue by mbosio85** [OHDSI/OncologyWG#293]
Hello,

At our workplace we would like to structure our databases to follow OHDSI specifications for our data which include several genetic variants + annotations.
I tried to backtrack the evolution of the genomic-CDM here and I am not sure which specifications are the latest.
On one side the section [genomics/data_model/Genomic CDM (open-public)/1. Specification/](https://github.com/OHDSI/OncologyWG/tree/master/genomics/data_model/Genomic%20CDM%20(open-public)/1.%20Specification) includes several tables like _genomic_test_, _variant_occurrence_, or _variant_annotation_

On the other side from the[ wiki page](https://github.com/OHDSI/OncologyWG/wiki/Mapping-of-Genomic-Data) about mapping genomic data to measurement table it looks that the measurement table could substitute some tables from the above version of the G-CDM. Plus there is a final slide with a minimized G-CDM information that I am unsure if it is a new table or is it mapped to one of the previous tables in the Genomic CDM.

My question is how to follow the latest recommendations to shape our database so that it is compatible with OHDSI. Is there a toy example somewhere about how to do it properly (which tables to include and with which fields) ? 

thanks,

Mattia

**Comment by cgreich** [comment]
Mattia:

This is very apropos. We are in the middle of a fierce battle with the various choices we have to represent genomic variants. The documentation online is lagging behind. Please come and join us. @sratwani will bring you in.

**Comment by mbosio85** [comment]
Thanks for the reply. It would be great to participate in the discussion if possible.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
