### ISSUE TITLE
Missing monotherapies in OncoRegimenFinder?

### ISSUE THREAD

**Issue by meerapatelmd** [OHDSI/OncologyWG#295]
Upon code review, came across the following in RegimenVoc.sql:

```
select c.*, (case when lower(reg_name) = regexp_replace(combo_name,',',' and ') then 0
else row_number() over (partition by combo_name order by length(c.reg_name)) end ) as rank
from CTE c
order by rank desc
),
```
In the HemOnc algorithms I've written, I normalize in the opposite direction. I replace `" and "` with `", "`, but also remove `" monotherapy"` in the concept_name if the name is a single drug regimen. 

I am double-checking that we aren't missing the monotherapies at this point since it is then filtered based on match and ranked further based on length if there isn't a match.

**Comment by siapstack** [comment]
Hey @sratwani and @golozara are you still interested in improving the package or have you moved to a new package? I would be happy to help. Anastasios
