### ISSUE TITLE
Q: OncoRegimenFinder package - antineoplastics that do not fall under the concept 21601387

### ISSUE THREAD

**Issue by ericammann** [OHDSI/OncologyWG#301]
Hi, I really enjoyed the Oncology WG presentations at OHDSI and came over straight away to test out the software packages!

Had a question about the use of the concept 21601387 to identify all drugs falling within the ATC2 class for antineoplastic agents. For multiple myeloma, some of the most commonly used agents in the US are the thalidomide-like IMiDs such as lenalidomide. These do not fall within concept 21601387. Is there a way of forcing these additional concepts into the vocabulary for identifying antineoplastics?

I also had another question about potentially limiting the list of antineoplastics considered to those commonly used for a particular indication of interest. For example, a multiple myeloma patient may continue to be on aromatase inhibitor maintenance for a prior malignancy, but one might want to ignore the aromatase inhibitor use in characterizing the patient's antimyeloma treatments.

**Comment by jeremywarner** [comment]
Hello Erica,

I was unable to join the OHDSI meeting this week, but I encourage you to check out the drug class hierarchy in HemOnc, which is available through OHDSI. I believe we have what you are looking for. For example:

Lenalidomide (35803149) is an Immunomodulatory drugs (IMiDs) (35807403) is an Immunotherapeutic (35807189) is an Antineoplastics by Class Effect (35807466) is a Drug (35802854) is an Intervention (35807465)

Working backwards, Immunomodulatory drugs (IMiDs) contains lenalidomide, pomalidomide, and thalidomide.

We also have extensive contextual relationships (indication of interest) - over 5000 in the latest release. These should also be available through OHDSI. Happy to discuss further, including if you are interested in full ontology (OHDSI has not consumed the clinical trial information, for example).

Best,
Jeremy

**Comment by ericammann** [comment]
Thanks Jeremy!

When I ran the OncoRegimenFinder package using the suggested syntax here as a model:
https://github.com/OHDSI/OncologyWG/tree/master/OncoRegimenFinderV3

The resulting cancer_regimen_ingredients file didn't include the thalidomide-like drugs. If I'm reading the relevant code here (lines 32-34) correctly

https://github.com/OHDSI/OncologyWG/blob/master/OncoRegimenFinderV3/SQL/RawEvents.sql

	and c.concept_id in (
		  select descendant_concept_id as drug_concept_id from @cdmDatabaseSchema.concept_ancestor ca1
		  where ancestor_concept_id in (@drug_classification_id_input) /* Drug concept_id  */ 

It appears that only drugs that have the concept 21601387 (ATC Level 2: Antineoplastic Agents) as their ancestor in the OMOP CDM Concept_Ancestor table are getting pulled to define the oncology therapeutic exposures and that the HemeOnc vocabulary  which does include lenalidomide wasn't being referenced at this step (?). Sorry if I'm missing something obvious here--I'm a newb. :)

**Comment by mgurley** [comment]
@ericammann Good debugging.  I think that the ingredients/components that the code uses to derive regimens should be based on the ingredients/components that Hemonc.org dictates.  Since the output is  Hemonc.org regimens we should be taking the components from Hemonc.org. Not ATC.  As is clear they don't completely agree.  @ansi90 What do you think?

**Comment by jeremywarner** [comment]
I wonder if it is necessary to have an explicit Maps to relationship between the HemOnc concept and 21601387 (ATC Level 2: Antineoplastic Agents)? Happy to add if this would help.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA, FASCO
Associate Professor of Medicine (Hematology/Oncology) and Biomedical Informatics at Vanderbilt University
Associate Editor, JCO Clinical Cancer Informatics
Deputy Editor, HemOnc.org

Jennifer Bauer
Interim Administrative Assistant
jennifer.m.bauer@vumc.org<mailto:jennifer.m.bauer@vumc.org>
615.875.4547

**Comment by golozara** [comment]
@ericammann You raised a very good point. The current package first identifies all drugs under ATC classification L01 "Antineoplastic Agents" and uses HemOnc to identify and create regimens. That is why drugs like Linalidomide won't be picked up. This is one areas we will be working on to improve in the next version. For the time being, you have the option to define those specific concepts (and the descendants) to be included when searching for treatments in the drug exposure table.

**Comment by ericammann** [comment]
Thanks all for your helpful comments! Following the suggestion from Asieh, I added codes for lenalidomide, thalidomide, pomalidomide, dexamethasone, and prednisone to my drug_classification_id_input parameter and am now seeing a lot more of the usual suspects for myeloma (e.g., bortezomib-lenalidomide-dexamethasone, lenalidomide-dexamethasone) in the output regimens table.

`create_regimens(connectionDetails = conn,
                cdmDatabaseSchema = "cdm",
                writeDatabaseSchema = "scratch_mm_lot_mdcr",
                cohortTable = "cancer_cohort",
                regimenTable = "cancer_regimens",
                regimenIngredientTable = "cancer_regimen_ingredients",
                vocabularyTable = "regimen_voc_upd",
                drug_classification_id_input = "21601387,21603926,1518254,43014237,21603928,1551099",
                date_lag_input = 30,
                regimen_repeats = 5,
                generateVocabTable = T)`

And I think this also answers my other question.  If I wanted to focus on a specific list of antimyeloma therapies and ignore antineoplastics that are more likely to be used for other cancers, I could just list concept_id values for specific drugs of interest and drop the broader "Antineoplastic agents" concept_id.

Eric
