### ISSUE TITLE
Standard Values with Non-standard Variables (NAAACCR)

### ISSUE THREAD

**Issue by VarvaraSav** [OHDSI/OncologyWG#308]
Hello!
During data analysis, we found some problems with NAAACCR: we noticed, that there are standard values with non-standard variables. The list of concepts you can see below:

3270 | RX Summ--Palliative Proc
1294 | RX Summ--Surg Oth Reg/Dis
1380 | RX Summ--Surg/Rad Seq
1285 | RX Summ--Treatment Status
1350 | RX Summ--DX/Stg Proc
1639 | RX Summ--Systemic/Sur Seq
1292 | RX Summ--Scope Reg LN Sur
1420 | RX Summ--Other
1360 | RX Summ--Radiation
1370 | RX Summ--Rad to CNS
1639 | RX Summ--Systemic/Sur Seq

The question is: how is it planning to add this data?
Thank you.

**Comment by cgreich** [comment]
They should all be mapped to Cancer Modifiers using the upcoming mapping tables. NAACCR should be turned non-standard.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
