### ISSUE TITLE
How should we handle versions of staging variables?  For both TNM and AJCC variables?

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#31]
Currently the SEER API only provides possible values for Union for International Cancer Control (UICC) TNM 7th edition classification?  TNM categories, stage groups, and definitions are based on the Union for International Cancer Control (UICC) TNM 7th edition classification. UICC 7th edition and AJCC 7th edition TNM categories and stage groups are very similar; however, there are some differences.

Should we try to obtain possible values for other TNM versions?  This would require that ETL writers would need to scope the look up of their staging variables with NAACCR item #1060 TNM Edition Number.  See here:http://datadictionary.naaccr.org/default.aspx?c=10#1060

**Comment by cgreich** [comment]
Sounds like a gigantic overkill if you think what the true use cases are going to be. Should we start simple and do only UICC? What are the differences? Do you have examples?

**Comment by cgreich** [comment]
BTW: It says in https://seer.cancer.gov/archive/manuals/2016/SPCSM_2016_SectionV.pdf:

"The rules of classification and staging in the UICC 7th edition correspond with those appearing in the seventh edition of the AJCC Cancer Staging Manual (2009) and have approval of all national TNM committees. (UICC, 7th edition, pg. 4)"

**Comment by mgurley** [comment]
At the 3/12/2019 Oncology Workgroup meeting we discussed various options.  @mgurley said that NAACCR informed him that the NAACCR #1060 TNM Edition Number controls which set of staging variables should be populated for a NAACCR case.  For example, NAACCR #880 TNM PATH T versus NAACCR  #1011 AJCC TNM PATH T.  So If TNM Edition Number = 'Eighth Edition (published 2016), recommended for use with cases diagnosed 2018+' then NAACCR  #1011 should be used. Otherwise, other AJCC editions should use NAACCR #880.  

@mgurley also discussed how staging cases in NAAACR stay bound to a staging version across upgrades of NAAACR verson.  For example, a NAACR case abstracted with 'AJCC Sixth Edition (published 2002), recommended for use for cases diagnosed 2003-2009' will not have its staging variables converted or upgraded to "Eighth Edition (published 2016), recommended for use with cases diagnosed 2018+"

@cgreich recommended that we not try to maintain separate versions of AJCC staging variables values across all versions, but instead create a unioned set of AJCC staging variables across all versions.  Perhaps we can see steal this from the Nebraska Lexicon.

**Comment by mgurley** [comment]
The beta test will prove if our approach is tenable.  For now closing.
