### ISSUE TITLE
Build EPISODE Table for Disease Episode (Disease Extent, Disease Dynamic, Overarching Disease Episode)

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#310]
Following steps are needed to build a Disease Episode from NAACCR
(1) For the initial entry into EPISODE from NAACCR 390 Date of Diagnosis, change the setting of EPISODE.episode_concept_id from using legacy 'Disease First Occurrence' to one entry for 'Disease Extent' and one entry for 'Disease Dynamic'.  Hard code 'Progression' for 'Disease Dynamic'.  Map 'Disease Extent' from summary staging.

(2) Verify that summary staging is available for all patients.

(3) Set episode number to '1' for both child disease episodes.

(4) Create subsequent child disease episode(s) from NAACCR 1880 RECURRENCE TYPE--1ST.  Use mapping done by Asieh.  Not all mappings will require both a 'Disease Dynamic' and 'Disease Extent' episode.  Use NAACCR 1860 RECURRENCE DATE--1ST for the setting of EPISODE.episode_begin_date.

(5) Create a 'Remission' 'Disease Dynamic' episode upon the insertion of the earliest Treatment Episode.

(6) Insert Overarching Disease Episode entry based on all child disease episodes. With EPISDOE.episode_object_concept_id = EPISODE.episode_object_concept_id  of the initial child.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
