### ISSUE TITLE
Changes for Treatment Episodes - Remove all insertion of entries into the clinical event tables

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#311]
Current : The current NAACCR ETL inserts entries in the DRUG_EXPOSURE table ** AND the EPISODE table for NAACCR treatments. It then makes an entry in EPISODE_EVENT to link them. However, since high-level treatments are not representable within the Drug domain, it currently inserts non-standard NAACCR concepts which is not beneficial. 

Proposed Change: This task is to have the NAACCR ETL stop inserting into DRUG_EXPOSURE, PROCEDURE_OCCURRENCE or EPISODE_EVENT for NAACCR treatments and only insert into the EPISODE table. With this change we also want to include not inserting treatment modifiers into MEASURMENT for the lower level DRUG_EXPOSUE and PROCEDURE_OCCURRENCE entries, since they will be going away.

** The NAACCR ETL also inserts into PROCEDURE_OCCURRENCE for radiotherapy and surgery.  And while those are not non-standard we should make the behavior consistent across all NAACCR treatments.

**Comment by mgurley** [comment]
Duplicated #383
