### ISSUE TITLE
How should we handle NAACCR provenance concepts?

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#32]
There are two types of provenance concepts: one describing diagnostic source (e.g. pathologist, clinician) and another describing record source (e.g. pathology report, EHR). Which one should we use? Or should we simply import these as separate Measurement entries?

**Comment by cgreich** [comment]
Record source should be incorporated into Type Concepts. Diagnostic source should be in provider_concept_id.

**Comment by mgurley** [comment]
At the 3/12/2019 Oncology Workgroup meeting we decided that they should be curated out of the first version of NAACCR ingestion.  They can be added later if someone has a use case.
