### ISSUE TITLE
Should we record dates as a separate measurement record.(e.g. Date regional lymph node dissection NAACCR #682)?

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#33]

**Comment by cgreich** [comment]
Why would we do that? We already have a time stamp.

**Comment by mgurley** [comment]
At the 3/12/2019 Oncology Workgroup meeting, we decided that these date-only NAACCR items should be recorded in MEASURMENT with only a measurement date.  Not sure if need to annotate date-only NAAACR items similar to numeric NAACCR items.
