### ISSUE TITLE
Convert the use of hardcoded lists of ICDO3, ICD9 and ICD10 codes to use the SNOMED hierachy.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#340]
For the initial diagnosis analysis.

**Comment by cgreich** [comment]
Not sure what the problem is. Hardcoded code lists to do what with SNOMED? Are you talking about mapping?

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
