### ISSUE TITLE
Standard vocabulary for NAACCR Disease codes (Initial Diagnosis & Recurring) -> Mapping (low-level events)

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#346]
This is to map the NAACCR Initial Diagnosis and Recurrence codes to low-level events as a part of the EPISODE mapping ETL step. 

NAACCR INITIAL DIAGNOSIS
(A) Current concept in the Episode domain is invalidated. It should be moved to Cancer Modifiers domain and reinstated as standard (32528 - OMOP4822259	Disease First Occurrence	Disease Extent	Non-standard	Invalid	Episode	Episode)

(B) All NAACCR variables representing extent of disease should be mapped/grouped into one of the following concepts. This is done to avoid complicated rules of mapping multiple modifiers representing these concepts to episodes:
•In situ disease – create new
•Local disease – create new
•Regional disease – create new
•Metastatic disease – create new

NAACCR RECURRENCE
•	First recurrence –create new
•	Remission – create new
•	In situ recurrence – create new
•	Local recurrence – create new
•	Regional recurrence – create new
•	Metastatic recurrence – create new

**Comment by mgurley** [comment]
Duplicates https://github.com/OHDSI/Vocabulary-v5.0/issues/664

Closing and placing in the deep backlog to focus the repository.
