### ISSUE TITLE
SQL Server DDL

### ISSUE THREAD

**Issue by PorterJosh** [OHDSI/OncologyWG#410]
# Problem Space

In your [SQL Server ddl](https://github.com/OHDSI/OncologyWG/blob/master/ddl/Sql%20Server/OMOP%20CDM%20sql%20server%20ddl%20Oncology%20Module.txt), there is a commented out section for the measurements table with some alter table statements that do not contain the proper SQL Server syntax.
# Proposed Solutions
Change `ALTER TABLE measurement ADD COLUMN modifier_of_event_id BIGINT NULL, ADD COLUMN modifier_of_field_concept_id INTEGER NULL;`
to 
`ALTER TABLE measurement ADD  modifier_of_event_id BIGINT NULL
ALTER TABLE MEASUREMENT ADD modifier_of_field_concept_id INTEGER NULL;`

**Comment by rtmill** [comment]
Realizing the confusion caused with the unfinished templates, and 'components' are for something else. Editing and removing label. Also added a standard 'issue' template
