### ISSUE TITLE
Map duplicate NAACCR to other NAACCR items.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#51]
NAACCR has duplicate NAACCR items for staging.  For example:

NAACCR Item 1013 (AJCC TNM Path M) and NAACCR Item 880 (TNM Path T).

We have decided to map NAACCR items to NAACCR items when it is appropriate.

**Comment by dimshitc** [comment]
1. TNM stages
Somehow there are no values provided for target concepts in the API thing.
Can we just map them in reverse order?
I mean:
1011 AJCC TNM Path T  Maps to  880 TNM Path T etc?

2. Radiation 
 'Phase 2 info or Phase 3 info' to 'Phase 1 corresponding info' is not a mapping in a way established in OHDSI.
If you want to get rid of these Phase 1, 2, 3, we need to create generic concepts like 'Dose per Fraction (therapy phase unspecified)' or just 'Dose per Fraction'.

**Comment by mgurley** [comment]
1. We can, however, 1011 is the more recently released variable.  So that was why I chose it.  Same across the board for the other staging variables. But the larger issue is that we do need to get the target concepts for 1011 (and the rest) because they cover AJCC/UICC version 8, the latest version of AJCC/UICC.  My idea is to obtain them from here: https://www.facs.org/-/media/files/quality-programs/cancer/ncdb/store_manual_2018.ashx?la=en
I have raised the issue of missing target concepts for variables to the maintainers of the SEER API.  See here: https://github.com/imsweb/staging-client-java/issues/65#issuecomment-507269184
2. This sounds like a good solution to me and what I actually hoped we would eventually do.

**Comment by mgurley** [comment]
So far this is what has been implemented in the OMOP vocabulary:


item_number | item_name | relationship_id | item_number | item_name
-- | -- | -- | -- | --
1011 | AJCC TNM Path T | Maps to | 880 | TNM Path T
1012 | AJCC TNM Path N | Maps to | 890 | TNM Path N
1013 | AJCC TNM Path M | Maps to | 900 | TNM Path M
1014 | AJCC TNM Path Stage Group | Maps to | 910 | TNM Path Stage Group
1001 | AJCC TNM Clin T | Maps to | 940 | TNM Clin T
1002 | AJCC TNM Clin N | Maps to | 950 | TNM Clin N
1003 | AJCC TNM Clin M | Maps to | 960 | TNM Clin M
1004 | AJCC TNM Clin Stage Group | Maps to | 970 | TNM Clin Stage Group

**Comment by denyskaduk** [comment]
Hello everyone. I help Dmitriy with duplication in NAACCR. We have some examples and want to share it. In attachment below you can find some groups of values which we want to deduplicate with suggestion of mapping to standard concept or creating a new one.
[NAACCR_value_dedup_smaple.xlsx](https://github.com/OHDSI/OncologyWG/files/3670861/NAACCR_value_dedup_smaple.xlsx)

**Comment by mgurley** [comment]
@denyskaduk 
Please create separate tickets for each of the questions in this spreadsheet.
