### ISSUE TITLE
Stage Group: Map NAACCR to Cancer Modifier

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#515]
Given the version is stored in a separate field, the utility of this is unknown. That said, these values need to be de-standardized and may as well map them to the appropriate (albeit higher-level) concepts - i.e. without version included. 

It will take a little extra work as the representation varies from typical numeric to roman numeral. 

Target: 
[stage_group_CancerModifier.csv](https://github.com/OHDSI/OncologyWG/files/12338082/stage_group_CancerModifier.csv)

Source: 
[stage_group_NAACCR.csv](https://github.com/OHDSI/OncologyWG/files/12338086/stage_group_NAACCR.csv)

**Comment by kzollove** [comment]
This table contains the destandardized NAACCR concepts: [concept_NAACCRtoCM.xlsx](https://github.com/OHDSI/OncologyWG/files/12344795/concept_NAACCRtoCM.xlsx)
This table contains the NAACCR concepts mapped to Cancer Modifier concepts: [concept_relationship_NAACCRtoCM.xlsx](https://github.com/OHDSI/OncologyWG/files/12344796/concept_relationship_NAACCRtoCM.xlsx)

### Snags/considerations:
1. There were three terms (occult, stage unknown, not applicable; one each for clin and path) in NAACCR that weren't represented in the stage_group_CancerModifier table.
- Occult had a [match in Athena](https://athena.ohdsi.org/search-terms/terms/1635594), but it was not clin/path specific so I mapped both NAACCR terms to that one concept. I also destandardized in concept table
- Stage unknown had no match that I could find, so I destandardized in concept table and did not map.
- Not applicable was already non-standard. I did not include it in concept or concept_relationship table

2. We just leave standard_concept blank if non-standard, correct? This is what I did

3. Changing valid_end_date for the standard concepts. Do we need to include a row in the concept table where standard concept has valid_end_date updated?

ex:
|concept_id|standard_concept|start          |end            |
|1               |                             |8/15/2023|12/31/2099|
|1               |       S                    |1/1/1970  |8/15/2023  |

**Comment by kzollove** [comment]
[concept_relationship_NAACCRtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12352411/concept_relationship_NAACCRtoCM.csv)
[concept_NAACCRtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12352412/concept_NAACCRtoCM.csv)
