### ISSUE TITLE
Stage Group: Map LOINC to Cancer Modifier

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#516]
Given the version is stored in a separate field, the utility of this is unknown. That said, these values need to be de-standardized and may as well map them to the appropriate (albeit higher-level) concepts - i.e. without version included.

It will take a little extra work as the representation varies from typical numeric to roman numeral.

Target: 
[stage_group_CancerModifier.csv](https://github.com/OHDSI/OncologyWG/files/12338120/stage_group_CancerModifier.csv)

Source:
[stage_group_LOINC.csv](https://github.com/OHDSI/OncologyWG/files/12338121/stage_group_LOINC.csv)

**Comment by kzollove** [comment]
This table contains the destandardized LOINC concepts: [concept_LOINCtoCM.xlsx](https://github.com/OHDSI/OncologyWG/files/12346031/concept_LOINCtoCM.xlsx)
This table contains the NAACCR concepts mapped to Cancer Modifier concepts: [concept_relationship_LOINCtoCM.xlsx](https://github.com/OHDSI/OncologyWG/files/12346032/concept_relationship_LOINCtoCM.xlsx)

### Snags/ considerations:
1. Simple non-matches, similar to NAACCR (Occult, not applicable, "Recurrent, unstaged, unknown, Stage X")
2. Lots of seemingly valid stages with no match in CM (T1B1, IVS, IIIE, etc.)

ALL LOINC terms were destandardized in the concept table, the "snags" were not included in the concept_relationship table (except occult, which has a close match in CM)

**Comment by kzollove** [comment]
How to handle "missing" stage, Stage IVE

**Comment by kzollove** [comment]
Final tables:
[concept_LOINCtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12420423/concept_LOINCtoCM.csv)
[concept_relationship_LOINCtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12420424/concept_relationship_LOINCtoCM.csv)
