### ISSUE TITLE
Stage Group: Map SNOMED to Cancer Modifier

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#517]
Given the version is stored in a separate field, the utility of this is unknown. That said, these values need to be de-standardized and may as well map them to the appropriate (albeit higher-level) concepts - i.e. without version included.

Target: 
[stage_group_CancerModifier.csv](https://github.com/OHDSI/OncologyWG/files/12338352/stage_group_CancerModifier.csv)

Source:
[stage_group_SNOMED.csv](https://github.com/OHDSI/OncologyWG/files/12338354/stage_group_SNOMED.csv)

**Comment by kzollove** [comment]
Just noting that the "target" concepts all specify clin/path. The source concepts from SNOMED don't go into that level of detail, so I am going to map to the "parent" target concepts that do not specify clin/path

**Comment by kzollove** [comment]
"missing" concepts (these are in SNOMED but not Cancer Modifier)
- Stage 1m 4127609 (also in Nebraska Lexicon)
- Stage 4s, 5, A, B,B1,B2,C,D,D1,D2 (assigning maps to Cancer Modifier "Stage {X}" 
  - example, there is no AJCC/UICC Stage 4s, so mapped to less specific Stage 4S
  - In many cases there are alternative target concepts "<otherGroup> Stage {x}" (ex. Dukes' Stage D, INSS Stage 4S), but there is no specificity in the source concept
 - Stage 6 3188117 is a nebraska Lexicon class with no match in Cancer Modifier or elsewhere (though WR Stage 6 4306465 in SNOMED exists as well)
 - Stage A1, A2, B3, C1, C2, C3 are not in Cancer Modifier but also exist in Nebraska Lexicon (as non-standard, mapped to these SNOMED terms)
 - Stages 4130406 is super class for all other concepts. It should be mapped to the new concept created to fix #519

**Comment by kzollove** [comment]
All source concepts that are not listed in the above comment were mapped to standard Cancer Modifier concepts here: [concept_relationship_SNOMEDtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12362363/concept_relationship_SNOMEDtoCM.csv)

All source concepts from the table above are destandardized here (even if no map was made): [concept_SNOMEDtoCM.csv](https://github.com/OHDSI/OncologyWG/files/12362364/concept_SNOMEDtoCM.csv)
