### ISSUE TITLE
Figure out how to obtain AJCC/UICC 8 edition TNM values NAACCR staging variables.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#52]
See background discussion here:

http://forums.ohdsi.org/t/lung-cancer-stage-ia3/7175/4

Also see issue submitted to SEER for possible resolution:

https://github.com/imsweb/staging-client-java/issues/65

**Comment by mgurley** [comment]
This looks like a promising place to get version 8 values:

https://www.facs.org/quality-programs/cancer/ncdb/registrymanuals/cocmanuals

At the meeting on 7/2/2019, it was decided to live with version 7 for the first version of ingestion NAACCR into the OMOP vocabulary tables.  Will revisit in next version.

**Comment by sratwani** [comment]
@dimshitc Can this be closed? I believe we are using NAACCR to obtain the AJCC variables?
