### ISSUE TITLE
Study: IEAI+PIONEER

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#546]
# Study:  IEAI+PIONEER Prediction Study

## Description 
// a brief introductory statement of intent

## Details
// details/requirements/goals of the study 

## Dependent Components 
- [x] #399 
- [ ] #511 
- [ ] #403 
- [ ] #416 
- [ ] #413 
- [ ] #449 
- [ ] #429 
- [x] #407 
- [ ] #469

**Comment by golozara** [comment]
Study ended.
