### ISSUE TITLE
Make FNCLCC grading concepts standard again

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#553]
While there are only 3 codes, they are currently duplicated so there are 6 concepts to change. 

Suggestion: Choose a set of three and standardize, map the other 3 to the new standards. 

Concepts:
[grade_fnclcc_concepts.xlsx](https://github.com/OHDSI/OncologyWG/files/12374128/grade_fnclcc_concepts.xlsx)

**Comment by kzollove** [comment]
3 concepts are set to standard in the concept table and the other 3 are unchanged.

In the concept_relationship table, the 3 newly standard concepts are mapped to/from themselves. The 3 non-standard are also mapped to/from the new standard concepts. Finally, the 3 new standard concepts are represented as children of the generic Cancer modifier Grade concepts  for example [Grade 1 Tumor](https://athena.ohdsi.org/search-terms/terms/1634371).

**Comment by cgreich** [comment]
> The harder part is how to represent (and execute) removing existing concept relationships using the simple concept/concept_relationship representation of vocabulary changes?

You don't. Go through the [Community Contribution](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution-guidelines:-non%E2%80%90drug-vocabularies) process. Making concepts standard is not yet there in self-service. Contact the Vocab Team.

**Comment by rtmill** [comment]
> > The harder part is how to represent (and execute) removing existing concept relationships using the simple concept/concept_relationship representation of vocabulary changes?
> 
> You don't. Go through the [Community Contribution](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution-guidelines:-non%E2%80%90drug-vocabularies) process. Making concepts standard is not yet there in self-service. Contact the Vocab Team.

@cgreich This is regarding the development sprint where we will be building and persisting a delta of the vocabularies to facilitate short-term adoption (and eventually be folded back into the standard vocabularies).

**Comment by kzollove** [comment]
Along with plan outlined above, all existing relationships are marked with invalid reason "D" in concept_relationship table

[concept_FNCLCC.csv](https://github.com/OHDSI/OncologyWG/files/12459055/concept_FNCLCC.csv)
[concept_relationship_FNCLCC.csv](https://github.com/OHDSI/OncologyWG/files/12459054/concept_relationship_FNCLCC.csv)
