### ISSUE TITLE
Create list of NAACCR grade concepts to destandardize

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#555]
"Variable" concepts:
35918519 [Grade Post Therapy](https://athena.ohdsi.org/search-terms/terms/35918519)
,35918542 [Grade Clinical](https://athena.ohdsi.org/search-terms/terms/35918542)
,35918640 [Grade Pathological](https://athena.ohdsi.org/search-terms/terms/35918640)

They seem to share the same value sets with many duplications (same name and meaning but from different NAACCR schemas). There are 121 unique "answer" concepts to destandardize but only 11 unique concept names to map and then apply to all. 

Unique concept names:
```
Grade cannot be assessed (GX); Unknown
Grade cannot be assessed; Unknown
Grade cannot be assessed (GX); Unknown |Not applicable
GB: Borderline Tumor
G3B: > 15 centroblasts per HPF and solid sheets of centroblasts
Grade cannot be assessed (GX); Unknown |Not a follicular histology (9690/3, 9691/3, 9695/3, 9698/3)
Low grade: Grade 1-2
G1: 0-5 centroblasts per HPF
TP53 or CTNNB Mutation
G2: 6-15 centroblasts per HPF
G3: > 15 centroblasts
G3A: >15 centroblasts per HPF and centrocytes present
```

Suggestion: Destandardize the "unknown" answers without mapping, then map the remaining. 

This boils it down even further to:
```
GB: Borderline Tumor
G3B: > 15 centroblasts per HPF and solid sheets of centroblasts
Low grade: Grade 1-2
G1: 0-5 centroblasts per HPF
TP53 or CTNNB Mutation
G2: 6-15 centroblasts per HPF
G3: > 15 centroblasts
G3A: >15 centroblasts per HPF and centrocytes present
```

**Comment by kzollove** [comment]
Borderline tumor still needs to be addressed in Cancer Modifier #568

**Comment by kzollove** [comment]
> GB: Borderline Tumor
Borderline tumor still needs to be addressed in Cancer Modifier https://github.com/OHDSI/OncologyWG/issues/568

> G3B: > 15 centroblasts per HPF and solid sheets of centroblasts
Do we need an explicit representation for FL grading?

> Low grade: Grade 1-2
> G1: 0-5 centroblasts per HPF
> TP53 or CTNNB Mutation
> G2: 6-15 centroblasts per HPF
> G3: > 15 centroblasts
> G3A: >15 centroblasts per HPF and centrocytes present
> ```

**Comment by kzollove** [comment]
>TP53 or CTNNB Mutation

I can see that this is a NAACCR grade concept, but I don't understand why. No existing mapping

**Comment by kzollove** [comment]
Add'l concepts I've ID'ed to be destandardized so far:

[concept_NAACCRtoCM_grade.csv](https://github.com/OHDSI/OncologyWG/files/12489000/concept_NAACCRtoCM_grade.csv)

**Comment by kzollove** [comment]
@rtmill can you explain this suggestion more?

> ```
> Grade cannot be assessed (GX); Unknown
> Grade cannot be assessed; Unknown
> Grade cannot be assessed (GX); Unknown |Not applicable
> ```
>
> Suggestion: Destandardize the "unknown" answers without mapping, then map the remaining.

**Comment by kzollove** [comment]
List of NAACCR concepts to destandardize

Source: [grade_NAACCR.csv](https://github.com/OHDSI/OncologyWG/files/13177829/grade_NAACCR.csv)
