### ISSUE TITLE
Missing 'Maps to' entries in CONCEPT_RELATIONSHIP for all NAACCR treatment variables.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#56]
In 'OMOP Standardized Vocabularies' version 'v5.0 09-JUL-19', there are no 'Maps to' entries in CONCEPT_RELATIONSHIP for any NAACCR treatment variables.  The  [curated](https://github.com/OHDSI/OncologyWG/blob/master/ohdsi-naaccr-ingestor/lib/data/naaccr_curated.xlsx) NAACCR spreadsheet instructed the following maps be made:

NAACCR Item #| NAACCR Item| Maps to
-- | -- | --
1290 | RX Summ--Surg Prim Site | domain_id: Episode,   concept_name: Treatment Regimen
1390 | RX Summ--Chemo | domain_id: Episode, concept_name: Treatment Regimen
1400 | RX Summ--Hormone | domain_id: Episode, concept_name: Treatment Regimen
1410 | RX Summ--BRM | domain_id: Episode, concept_name: Treatment Regimen
1506 | Phase I Radiation Treatment Modality | domain_id: Episode, concept_name: Treatment Regimen
1516 | Phase II Radiation Treatment Modality | domain_id: Episode, concept_name: Treatment Regimen
1526 | Phase III Radiation Treatment Modality | domain_id: Episode, concept_name: Treatment Regimen
3250 | RX Summ--Transplnt/Endocr | domain_id: Episode, concept_name: Treatment Regimen

**Comment by dimshitc** [comment]
make values of these concepts standard as well except for flawors of NULL.

**Comment by mgurley** [comment]
@dimshitc yes exaclty
