### ISSUE TITLE
How to structure a tumor grade hierarchy to enable searchability in Cancer Modifier

### ISSUE THREAD

**Issue by kzollove** [OHDSI/OncologyWG#569]
One example of top-level grade concept https://athena.ohdsi.org/search-terms/terms/35918328

**Comment by rtmill** [comment]
The issue: The values within Staging and grading are the top of their respective hierarchies. To make it searchable and easy to navigate, should we insert relations to parent concepts to group them?

Examples:
[Grade 1 tumor](https://athena.ohdsi.org/search-terms/terms/1634371) has no parent concept
[TNM and Stage Group](https://athena.ohdsi.org/search-terms/terms/734320) both have the highest level concept as "AJCC/UICC finding"

The goal would be to have concepts a user could click on and then navigate all standard concepts that fit within "grade", "stage", etc, as right now there is no grouper for them. 

Option A) Create new concepts within Cancer Modifier to encapsulate these groups
Option B) Leverage a grouper concept from another vocabulary (e.g. SNOMED), assuming all child-concepts are de-duplicated
Option C) Another plan

**Comment by rtmill** [comment]
Covered by #558 - proposal will go there

**Comment by rtmill** [comment]
Duplicate content of #558 

Comments copied from this ticket over to that one. 

Closing this ticket.
