### ISSUE TITLE
Create a mapping table to be used for handling ambiguous ICDO site/histology combinations present in multiple schemas.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#59]
Here is the format.

icdo_site_histology | naaccr_item | naaccr_item_code | sex | csfactor25 | naaccr_item_omop_concept_id | naaccr_item_code_omop_concept_id
-- | -- | -- | -- | -- | -- | --

**Comment by sratwani** [comment]
Same as https://github.com/OHDSI/OncologyWG/issues/113. Closing. Please reference 113.
