### ISSUE TITLE
Ingest NAACCR into the OMOP vocabulary tables.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#6]
- Call the SEER API to ingest into the OHDSI vocabulary tables NAACCR data item/data item categorical values.
  - Get an account and API key from here: https://api.seer.cancer.gov/new_account
  - Return all NAACCR item numbers/item names for the latest NAACCR version from this REST resource: https://api.seer.cancer.gov/rest/naaccr/latest.   This will return an array of hashes for reach NAACCR data item with the following JSON object structure: { "item": 10, "name": "Record Type" }
  - For each NAACCR data item, call the REST resource (replacing 10 with each NAACCR data item number): https://api.seer.cancer.gov/rest/naaccr/latest/item/10.  This will return a hash with the following structure (the “documentation” key value can be seen in the separate file ‘documentation.html’): { "item": 1390, "name": "RX Summ--Chemo", "start_col": 2243, "end_col": 2244, "alignment":  "RIGHT","padding_char": "0", "documentation": “documentation.html”  }
    - Parse the HTML value in the “documentation’ key.  Here are CSS selectors that will help you find the right content:  
      - ‘div.content.chap10-para .code-row’  This will find each categorical value for the NACCAR data item.
      - ‘td.code-nbr’ to find the code value
      - ‘td.code-dsc’ to find the code description.
  - Not all NAACCR data items will have its list of categorical values within the ‘documentation’ key.  Some NAACCR data items are non-categorical.  Other NAACCR data items are what is called ‘site-specific’ (SSDI). SSDI means the data item’s categorical values are based on the anatomical site/topography being reported upon.   For example:
    - NAACCR data item #1290 ‘RX SUMM--SURG PRIM SITE’: tracks the site-specific codes for the type of surgery to the primary site performed as part of the first course of treatment. This includes treatment given at all facilities as part of the first course of treatment.   Here are the high-level grouping of site-specific surgery codes.
      - 00	None
      - 10-19	Site-specific code; tumor destruction
      - 20-80	Site-specific codes; resection
      - 90	Surgery, NOS
      - 98	Site specific codes; special
      - 99	Unknown
  - Return all NAACCR site-specific surgery codes table titles from this REST resource: https://api.seer.cancer.gov/rest/surgery/latest/tables.  This will return an array of strings each string representing a site-specific surgery codes table title.  Each table tile is a short hand for a group of anatomical ICDO site codes.
  - For each NAACCR site-specific surgery codes table title, call the REST resource (replacing ‘Breast’ with each NAACCR site-specific surgery code table title):  https://api.seer.cancer.gov/rest/surgery/latest/table?title=Breast.  This will return a hash with the following structure (the “row” key value can be seen in the separate file ‘row.json’): { "title": "Breast", "site_inclusions": "C500-C509", "hist_exclusions": "9727,9733,9741-9742,9764-9809,9832,9840-9931,9945-9946,9950-9967,9975-9992", "pre_note": "C500-C509<br/>(Except for M-9727, 9733, 9741-9742, 9764-9809, 9832, 9840-9931, 9945-9946, 9950-9967 and 9975-9992)", "row":[ {}, {}]}.  The “site_inclusions” key details the range of ICDO topography/anatomical sites bound to this list of surgery codes.  The “row” key is an array of hashes that represents the site-specific surgery code hierarchy.  Some of the hashes in the “row” key are for line-break formatting and instructional text.  Ignore all entries in the “row” key with a “line_break”: true key/value pair or that have a “code”:”” key/value pair.  The hierarchal structure of the “row” key is based on the order of the entries.  The “level” key can go from 0 to 3. 
- Screen scrape the NAACCR EOD data SSDI data item possible values.  A whole set of all SSDI NAACCR data items fall into the category ‘EOD Data’.  See here a list of EOD schemas (anatomical site/histology groupings): https://staging.seer.cancer.gov/eod_public/list/1.4/.  Unfortunately, it does not appear that the SEER API yet supports detailing the list of possible values for these data items.  So we will need to scrape.
  - Visit https://staging.seer.cancer.gov/eod_public/list/1.4/
  - Click each “schema”.
  - Scrape the list of possible ‘Primary Site’ and ‘Histology’ associated with the “schema”.
  - For each row in the table labeled “Data Items”, if the “Metadata” column indicates “SSDI”, click on the link in the “Name” column.
  - On the page for the SSDI NAACCR data item, scrape the NAACCR data item and collect the possible values from the table with the headers “Code” and “Description”.
- Screen scrape the NAACCR TNM data SSDI data item possible values.  A whole set of all SSDI NAACCR data items fall into the category ‘TNM Data’.  See here a list of TNM schemas (anatomical site/histology groupings): https://staging.seer.cancer.gov/tnm/list/1.9/ .  Unfortunately, it does not appear that the SEER API yet supports detailing the list of possible values for these data items.  So we will need to scrape.
  - Visit https://staging.seer.cancer.gov/tnm/list/1.9/
  - Click each “schema”.
  - Scrape the list of possible ‘Primary Site’ and ‘Histology’ associated with the “schema”.
  - For each row in the table labeled “Main Data Items”, click on the link in the “Name” column.
  - On the page for the SSDI NAACCR data item, scrape the NAACCR data item and collect the possible values from the table with the header specific the SSDI data item.  For example, 'Clinical T' and 'Clinical T Display’.

[row.json](https://drive.google.com/open?id=16k4_jS8HxK1CpLbkrxHjEAfVMyOBXSXU)
[documentation.html](https://drive.google.com/open?id=11Cl2pXYM3e84TWOXKlhht3ssCVjKbEJ_)

**Comment by mgurley** [comment]
See first swipe by @dimshitc here:
https://docs.google.com/spreadsheets/d/1t4MlNxRmCTuEeFockb58boiqNf4xSgwKe2TuybQ5plQ/edit#gid=1970199715

**Comment by mgurley** [comment]
Rimma's instructions:
- Parse   into computable format.
- Describe treatment variables.
- Pick candidate sites: breast, brain, prostate
- Pick attributes based on use cases.
- Only import attributes/values that make cut.

**Comment by mgurley** [comment]
@dimshitc 
I used this NAACCR website to filter the list of relevant NAACCR items down to a more manageable size based on the Section each item belongs to ('Cancer Identification', 'Stage/Prognostic Factors', 'Treatment-1st Course', 'Treatment-Subsequent & Other')

http://applications.naaccr.org/querybuilder/default.aspx?Version=18

Here is the filtered list:

[naaccr_questions_filtered.xlsx](https://github.com/OHDSI/OncologyWG/files/2633998/naaccr_questions_filtered.xlsx)

**Comment by mgurley** [comment]
Here is @dimshitc first cut at putting NAACCR into a computable format:

https://docs.google.com/spreadsheets/d/1dEvy9xWhEfy-AnjhItMOe5MHbaUUrMZwSk2rZCzxO0k/edit?usp=sharing

**Comment by dimshitc** [comment]
**Procedures**
general idea:
Map their sites to SNOMED, if not possible - create a new standard concept.
then build relationships.
For example:
we have the procedure code "50" for Total proctectomy in "Rectosigmoid" Site.
we create a new concept with
concept_code = 'Proc_50_Rectosigmoid' = 'Proc_'||code||'_'||schema 
concept_name= 'Total proctectomy'
vocabulary_id ='NAACCR'
and build the relationships:
'Proc_50_Rectosigmoid' | Maps to | 235364003 (Total proctectomy - SNOMED)
'Proc_50_Rectosigmoid' | Has Site (NAACCR) | 81922002 Rectosigmoid structure (SNOMED)
Note, I used **concept_codes** for SNOMED in the example

details:
1. Manually identify the procedures needed to be concatenated with their parent concepts description to make a correct name
e.g.
source: Ovary | 27 |	"WITHOUT hysterectomy" | parent_concept = 25 "Total removal of tumor or (single) ovary, NOS"
omop: Proc_27_Ovary | "Total removal of tumor or (single) ovary, NOS, WITHOUT hysterectomy"

2. A lot of procedure codes itself have the same meaning regardless of the site, for example "10	Local tumor destruction, NOS"
But anyway, we create a separate procedure for each site, right?
e.g
source: 10	| Local tumor destruction, NOS |	Bladder 
omop: Proc_10_Bladder | "Local tumor destruction, NOS of Bladder"

**Comment by dimshitc** [comment]
**Histological grades:**
NAACCR #3843 Grade Clinical
NAACCR #3844 Grade Pathological
NAACCR #3845 Grade Post Therapy 
share the same bunch of values within the site

1	G1: Well differentiated
2	G2: Moderately differentiated
3	G3: Poorly differentiated
4	G4: Undifferentiated
8	Not applicable
9	Grade cannot be assessed (GX); Unknown

with same unsignificant name variations:
1	WHO Grade I : Circumscribed tumors of low proliferative potential associated with the possibility of cure following resection (Brain)
1	G1: Low combined histologic grade (favorable), SBR score of 3-5 points (Breast)
or 
2	WHO Grade II: Infiltrative tumors with low proliferative potential with increased risk of recurrence (Brain)
2	G2: Intermediate combined histologic grade (moderately favorable); SBR score of 6-7 points

A	Well differentiated
B	Moderately differentiated
C	Poorly differentiated
D	Undifferentiated, anaplastic
E	Stated as ""Gleason score 7"" with no patterns documented or Any Gleason patterns combination equal to 7 not specified in 2 or 3 - exists only for Prostate

H	High grade
L	Low grade

M	TP53 or CTNNB Mutation - Adrenal Gland 
M	Nuclear Grade II (interMediate) (in situ only) - Breast
S	Sarcomatous overgrowth - Corpus Adenosarcoma only

each site uses only numbers OR only letters with number 9 (unknown), 1-4 is synonymical to A-D though  

How to create a concept
for all in this way:
concept_code = 'Grade_1'
concpet_name = 'G1: Well differentiated'

except "M":
concept_code = 'Grade_M_Adranal_Gland'
concpet_name = 'TP53 or CTNNB Mutation'

concept_code = 'Grade_M_Adranal_Breast'
concpet_name = 'Nuclear Grade II (interMediate) (in situ only)'


should we neglect the name difference?
is it the right way to represent the concept codes?

**Comment by mgurley** [comment]
@dimshitc @rimusia 

Rimma and I are going to outline two possible ways to ingest NAACCR into the OMOP vocabulary tables.   I will document the options in this issue.  Then we will meet to discuss the options.

**Comment by mgurley** [comment]
We should only ingest into the OMOP vocabulary tables NAACCR data items from the following NAACCR sections:
- 'Cancer Identification'
-  'Stage/Prognostic Factors'
- 'Treatment-1st Course'

This covers 442 NAACCR items.  This will help us focus on the good stuff in NAACCR and weed out the cruft.

Some NAACCR items are **site-independent** and some are **site-dependent**.

- **Site-independent** means that the NAACCR item **is not bound** to an an ICD-O-3 site/histology combination and the NAACCR item's list of possible values **does not** depend/alter based on the ICD-O-3 site/histology combination of the tumor diagnosis it describes/applies to.
- **Site-dependent** means that the NAACCR item **is bound** to an an ICD-O-3 site/histology combination and possibly the NAACCR item's list of possible values **does** depend/alter based on the ICD-O-3 site/histology of the tumor diagnosis it describes/applies to.

### Ingesting Site-independent NAACCR Items into the OMOP Vocabulary Tables
Site-independent NAACCR items should be rather straightforward to ingest into the OMOP vocabulary tables.  For example, the NAACCR item \#410 'Laterality' should be ingested like so:

**CONCEPT**

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
1| Laterality|NAACCR|Measurement|Cancer Identification|S|410|1970-01-01|2099-12-31|
2| Not a paired site|NAACCR|Meas Value|Cancer Identification|S|0|1970-01-01|2099-12-31|
3| Right: origin of primary|NAACCR|Meas Value|Cancer Identification|S|1|1970-01-01|2099-12-31|
4| Left: origin of primary|NAACCR|Meas Value|Cancer Identification|S|2|1970-01-01|2099-12-31|
5|Only one side involved, right or left origin unspecified|NAACCR|Meas Value|Cancer Identification|S|3|1970-01-01|2099-12-31|
6|Bilateral involvement at time of diagnosis, lateral origin unknown for a single primary; or both ovaries involved simultaneously, single histology; bilateral retinoblastomas; bilateral Wilms' tumors|NAACCR|Meas Value|Cancer Identification|S|4|1970-01-01|2099-12-31|
7|Paired site: midline tumor|NAACCR|Meas Value|Cancer Identification|S|5|1970-01-01|2099-12-31|
8|Paired site, but no information concerning laterality|NAACCR|Meas Value|Cancer Identification|S|9|1970-01-01|2099-12-31|

**CONCEPT_RELATIONSHIP**

concept_id_1|concept_id_2| relationship_id |valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|
1|2|Has Answer|1970-01-01|2099-12-31||
2|1|Answer of|1970-01-01|2099-12-31||
1|3|Has Answer|1970-01-01|2099-12-31||
3|1|Answer of|1970-01-01|2099-12-31||
1|4|Has Answer|1970-01-01|2099-12-31||
4|1|Answer of|1970-01-01|2099-12-31||
1|5|Has Answer|1970-01-01|2099-12-31||
5|1|Answer of|1970-01-01|2099-12-31||
1|6|Has Answer|1970-01-01|2099-12-31||
6|1|Answer of|1970-01-01|2099-12-31||
1|7|Has Answer|1970-01-01|2099-12-31||
7|1|Answer of|1970-01-01|2099-12-31||
1|8|Has Answer|1970-01-01|2099-12-31||
8|1|Answer of|1970-01-01|2099-12-31||

### Ingesting Site-dependent NAACCR Items into the OMOP Vocabulary Tables
Site-dependent NAACCR items are not as straightforward to ingest into the OMOP vocabulary tables.  There are 3 different bindings of site-dependent NAACCR items:

- SEER EOD (Extent of Disease) Data : https://staging.seer.cancer.gov/eod_public/list/1.4/
- SEER TNM (Tumour Node Metastasis) Data: https://staging.seer.cancer.gov/tnm/list/1.9/
- NAACCR SSDI (Site Specific Data Items): https://apps.naaccr.org/ssdi/list/

SEER EOD includes NAACCR SSDI.  So we can focus on SEER EOD and SEER TNM.  Both of these bindings are bound to schemas.   Schemas are high-level names of anatomic sites that bundle combinations of ICD-O-3 site/histology.  The schemas for SEER EOD and SEER TNM overlap but are not equivalent.  Some schema examples:

Binding|Schema|Primary Site| Histology |
------------ | -------------|-------------|-------------|
EOD|Prostate|C619|8000-8700, 8720-8790, 9700-9701|
TNM|Prostate|C619|8000-8110, 8140-8576, 8940-8950, 8980-8981|
EOD|Adrenal Gland|C740-C741, C749|8000-8671, 8681-8683, 8691, 8720-8790, 9700-9701|
TNM|Adrenal Gland|C740|8010, 8140, 8370|
TNM|Adrenal Gland|C749|8370|

Some of the NAACCR items bound to an EOD schema/TNM schema have possible values that **do not** vary based on schema.  Some of the NAACCR items bound to an EOD schema/TNM schema have possible values that **do** vary based on schema.  

Here is an examples of a non-varying NAACCR item from two EOD schemas:

Binding|Schema|NAACCR Itiem \#|NAACCR Itiem Name |
------------ | -------------|-------------|-------------|
EOD|Adrenal Gland|NAACCR #1182|Lymphvascular Invasion(LVI)|
EOD|Prostate|NAACCR #1182|Lymphvascular Invasion(LVI)|

This NAACCR item can be ingested into the OMOP vocabulary tables like so:

**CONCEPT**

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
1| Lymphvascular Invasion|NAACCR|Measurement|Stage/Prognostic Factors|S|1182|1970-01-01|2099-12-31|
2| Lymph-vascular Invasion stated as Not Present|NAACCR|Meas Value|Stage/Prognostic Factors|S|0|1970-01-01|2099-12-31|
3| Lymphovascular Invasion Present/Identified|NAACCR|Meas Value|Stage/Prognostic Factors|S|1|1970-01-01|2099-12-31|
4| Lymphatic and small vessel invasion only (L)|NAACCR|Meas Value|Stage/Prognostic Factors|S|2|1970-01-01|2099-12-31|
5|Venous (large vessel) invasion only (V)|NAACCR|Meas Value|Stage/Prognostic Factors|S|3|1970-01-01|2099-12-31|
6|BOTH lymphatic and small vessel AND venous (large vessel) invasion|NAACCR|Meas Value|Stage/Prognostic Factors|S|4|1970-01-01|2099-12-31|
7|Not Applicable|NAACCR|Meas Value|Stage/Prognostic Factors|S|8|1970-01-01|2099-12-31|
8|Unknown/Indeterminate/not mentioned in path report|NAACCR|Meas Value|Stage/Prognostic Factors|S|9|1970-01-01|2099-12-31|

**CONCEPT_RELATIONSHIP**

concept_id_1|concept_id_2| relationship_id |valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|
1|2|Has Answer|1970-01-01|2099-12-31||
2|1|Answer of|1970-01-01|2099-12-31||
1|3|Has Answer|1970-01-01|2099-12-31||
3|1|Answer of|1970-01-01|2099-12-31||
1|4|Has Answer|1970-01-01|2099-12-31||
4|1|Answer of|1970-01-01|2099-12-31||
1|5|Has Answer|1970-01-01|2099-12-31||
5|1|Answer of|1970-01-01|2099-12-31||
1|6|Has Answer|1970-01-01|2099-12-31||
6|1|Answer of|1970-01-01|2099-12-31||
1|7|Has Answer|1970-01-01|2099-12-31||
7|1|Answer of|1970-01-01|2099-12-31||
1|8|Has Answer|1970-01-01|2099-12-31||
8|1|Answer of|1970-01-01|2099-12-31||
1|Every EOD SNOMED ICD-O site/histology combination|Has cancer site binding|1970-01-01|2099-12-31||
Every EOD SNOMED ICD-O site/histology combination|1|Cancer site binding of|1970-01-01|2099-12-31||

Here is an examples of a NAACCR item that has varying possible values across EOD schemas:

Binding|Schema|NAACCR Itiem \#|NAACCR Itiem Name |
------------ | -------------|-------------|-------------|
EOD|Adrenal Gland|NAACCR #3844|Grade Pathological|
EOD|Prostate|NAACCR #3844|Grade Pathological|

This NAACCR item can be ingested into the OMOP vocabulary tables like so:

**CONCEPT**

concept_id| concept_name | domain_id |vocabulary_id|concept_class_id|standard_concept|concept_code|valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-----------
1| Grade Pathological Adrenal|NAACCR|Measurement|Stage/Prognostic Factors|S|3844-Adrenal|1970-01-01|2099-12-31|
2|LG: Low grade (≤20 mitoses per 50 HPF)|NAACCR|Meas Value|Stage/Prognostic Factors|S|L|1970-01-01|2099-12-31|
3|HG: High grade (>20 mitosis per 50 HPF)|NAACCR|Meas Value|Stage/Prognostic Factors|S|H|1970-01-01|2099-12-31|
4| TP53 or CTNNB Mutation|NAACCR|Meas Value|Stage/Prognostic Factors|S|M|1970-01-01|2099-12-31|
5|Well differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|A|1970-01-01|2099-12-31|
6|Moderately differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|B|1970-01-01|2099-12-31|
7|Poorly differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|C|1970-01-01|2099-12-31|
8|Undifferentiated, anaplastic|NAACCR|Meas Value|Stage/Prognostic Factors|S|D|1970-01-01|2099-12-31|
9|Grade cannot be assessed (GX); Unknown|NAACCR|Meas Value|Stage/Prognostic Factors|S|9|1970-01-01|2099-12-31|
10| Grade Pathological Prostate|NAACCR|Measurement|Stage/Prognostic Factors|S|3844-Prostate|1970-01-01|2099-12-31|
11|Grade Group 1: Gleason score less than or equal to 6|NAACCR|Meas Value|Stage/Prognostic Factors|S|1|1970-01-01|2099-12-31|
12|Grade Group 2: Gleason score 7 Gleason pattern 3+4|NAACCR|Meas Value|Stage/Prognostic Factors|S|2|1970-01-01|2099-12-31|
13| Grade Group 3: Gleason score 7 Gleason pattern 4+3|NAACCR|Meas Value|Stage/Prognostic Factors|S|3|1970-01-01|2099-12-31|
14|Grade Group 4: Gleason score 8|NAACCR|Meas Value|Stage/Prognostic Factors|S|4|1970-01-01|2099-12-31|
15|Grade Group 5: Gleason score 9 or 10|NAACCR|Meas Value|Stage/Prognostic Factors|S|5|1970-01-01|2099-12-31|
16|Well differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|A|1970-01-01|2099-12-31|
17|Moderately differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|B|1970-01-01|2099-12-31|
18|Poorly differentiated|NAACCR|Meas Value|Stage/Prognostic Factors|S|C|1970-01-01|2099-12-31|
19|Undifferentiated, anaplastic|NAACCR|Meas Value|Stage/Prognostic Factors|S|D|1970-01-01|2099-12-31|
20|Stated as "Gleason score 7" with no patterns documented or Any Gleason patterns combination equal to 7 not specified in 2 or 3|NAACCR|Meas Value|Stage/Prognostic Factors|S|E|1970-01-01|2099-12-31|
21|Grade cannot be assessed; Unknown|NAACCR|Meas Value|Stage/Prognostic Factors|S|9|1970-01-01|2099-12-31|


**CONCEPT_RELATIONSHIP**

concept_id_1|concept_id_2| relationship_id |valid_start_date|valid_end_date|invalid_reason
------------ | -------------|-------------|-------------|-------------|-------------|
1|2|Has Answer|1970-01-01|2099-12-31||
2|1|Answer of|1970-01-01|2099-12-31||
1|3|Has Answer|1970-01-01|2099-12-31||
3|1|Answer of|1970-01-01|2099-12-31||
1|4|Has Answer|1970-01-01|2099-12-31||
4|1|Answer of|1970-01-01|2099-12-31||
1|5|Has Answer|1970-01-01|2099-12-31||
5|1|Answer of|1970-01-01|2099-12-31||
1|6|Has Answer|1970-01-01|2099-12-31||
6|1|Answer of|1970-01-01|2099-12-31||
1|7|Has Answer|1970-01-01|2099-12-31||
7|1|Answer of|1970-01-01|2099-12-31||
1|8|Has Answer|1970-01-01|2099-12-31||
8|1|Answer of|1970-01-01|2099-12-31||
1|9|Has Answer|1970-01-01|2099-12-31||
9|1|Answer of|1970-01-01|2099-12-31||
1|Every EOD Adrenal SNOMED ICD-O site/histology combination|Has cancer site binding|1970-01-01|2099-12-31||
Every EOD Adrenal SNOMED ICD-O site/histology combination|1|Cancer site binding of|1970-01-01|2099-12-31||
10|11|Has Answer|1970-01-01|2099-12-31||
11|10|Answer of|1970-01-01|2099-12-31||
10|12|Has Answer|1970-01-01|2099-12-31||
12|10|Answer of|1970-01-01|2099-12-31||
10|13|Has Answer|1970-01-01|2099-12-31||
13|10|Answer of|1970-01-01|2099-12-31||
10|14|Has Answer|1970-01-01|2099-12-31||
14|10|Answer of|1970-01-01|2099-12-31||
10|15|Has Answer|1970-01-01|2099-12-31||
15|10|Answer of|1970-01-01|2099-12-31||
10|16|Has Answer|1970-01-01|2099-12-31||
16|10|Answer of|1970-01-01|2099-12-31||
10|17|Has Answer|1970-01-01|2099-12-31||
17|10|Answer of|1970-01-01|2099-12-31||
10|18|Has Answer|1970-01-01|2099-12-31||
18|10|Answer of|1970-01-01|2099-12-31||
10|19|Has Answer|1970-01-01|2099-12-31||
19|10|Answer of|1970-01-01|2099-12-31||
10|20|Has Answer|1970-01-01|2099-12-31||
20|10|Answer of|1970-01-01|2099-12-31||
10|21|Has Answer|1970-01-01|2099-12-31||
21|10|Answer of|1970-01-01|2099-12-31||
10|Every EOD Prostate SNOMED ICD-O site/histology combination|Has cancer site binding|1970-01-01|2099-12-31||
Every EOD Prostate SNOMED ICD-O site/histology combination|10|Cancer site binding of|1970-01-01|2099-12-31||

**Comment by mgurley** [comment]
@dimshitc That is a typo.  Sorry. I will fix. The domain for most NAACCR attributes/questions should be 'Measurement' and for NAACCR values/answers should be 'Meas Value'  I will correct.  The vocabulary_id should be NAACCR.  Some treatment-related NAACCR attributes/questions values/answers will be in the new Treatment domain (I will worki on the Treatment NAACCR items/item answers this weekend).

**Comment by mgurley** [comment]
The first version of this has been completed.
