### ISSUE TITLE
The concept_codes to Surgery NAACCR item codes use NAACCR schema concept_names instead of NAACCR schemaconcept_codes.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#61]
The concept_codes for Surgery NAACCR item codes use the NAACCR schema concept_name instead of the concept_code.  For example, concept_id 35916758 has a concept_code='Cervix Uteri@1290@53'.  To be consistent with how the oncology diagnosis modifier concepts are encoded, this should instead be: cervix@1290@53.

**Comment by dimshitc** [comment]
Somehow we ended up with own procedure schemas (different from those usual NAACCR schemas). And yes, it's another work that still needs to be done, to map Procedure schemas to usual NAACCR schemas.

**Comment by mgurley** [comment]
@dimshitc Ah, so I need to use 'ICDO to Proc Schema' to instead of 'ICDO to Schema' for relationship_id.  I will try that.  NAACCR/SEER has different schemas for procedures versus diagnosis modifiers, so that explains the "somehow".  Can we get the NAACCR OMOP ingestion code in a public repository?

**Comment by mgurley** [comment]
Ok, I have now tried using 'ICDO to Proc Schema'. The necessary relationships between 'NAACCR Proc Schema' and 'ICDO Condition' entries do not seem to be present.  Closing this issue.  Entering new one #64.
