### ISSUE TITLE
Make EPISODE.episode_end_datetime nullable.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#63]

**Comment by MelaniePhilofsky** [comment]
@mgurley What was the resolution to making the EPISODE.episode_end_datetime nullable? It is still required in Postgres and nullable in RedShift.

**Comment by mgurley** [comment]
@MelaniePhilofsky 

It should be NULLABLE across the board on all platforms.  See the latest DDL here:
https://github.com/OHDSI/OncologyWG/tree/master/ddl

I think they are consistent.

We have another issue to get the extension tables into an OMOP official release that is not yet completed:
https://github.com/OHDSI/OncologyWG/issues/118
