### ISSUE TITLE
The 'NAACCR Proc Schema' entries do not have all the necessary relationships to ICDO codes via 'Proc Schema to ICDO'

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#64]
For example, the 'Prostate' 'NAACCR Proc Schema' seems to only have entries related to a small subset of the appropriate histologies.  Some SQL:

<pre>
select   c1.concept_name
       , c1.concept_class_id
       , c1.concept_code          
       , c2.concept_name
       , c2.concept_class_id
       , c2.concept_code          
       , c3.concept_name
       , c3.concept_class_id
       , c3.concept_code           
       , c4.concept_name
       , c4.concept_class_id
       , c4.concept_code
       , cr4.relationship_id
from concept c1 join concept_relationship cr1 on c1.concept_id = cr1.concept_id_1 and cr1.relationship_id = 'Has Answer'
                join concept c2 on cr1.concept_id_2 = c2.concept_id
                join concept_relationship cr2 on c2.concept_id = cr2.concept_id_1 and cr2.relationship_id = 'Value to Schema'
                join concept c3 on c3.concept_id = cr2.concept_id_2
                join concept_relationship cr3 on c3.concept_id = cr3.concept_id_1 and cr3.relationship_id = 'Proc Schema to ICDO'
                join concept c4 on cr3.concept_id_2 = c4.concept_id
                join concept_relationship cr4 on c4.concept_id = cr4.concept_id_1 and cr4.relationship_id = 'ICDO to Proc Schema'
and c1.concept_code = '1290'
AND c3.concept_name = 'Prostate'
order by     c3.concept_name

</pre>

According the SEER API, https://api.seer.cancer.gov/rest/surgery/latest/table?title=Prostate, the appropriate combinations should be the following:

"site_inclusions": "C619",
"hist_exclusions": "9727,9732,9741-9742,9762-9809,9832,9840-9931,9945-9946,9950-9967,9975-9992,3250"

So that would mean every combination of C619 and histologies not included above.  Right now, the most common Prostate Cancer histology (8140/3) is not associated with the 'Prostate' 'NAACCR Proc Schema'.   See documentation here:
https://training.seer.cancer.gov/prostate/abstract-code-stage/morphology.html

**Comment by dimshitc** [comment]
Should we make direct connection between NAACCR procedure and ICDO condition?
So, it saves one concept_relationship join, and make it more user-friendly.

**Comment by dimshitc** [comment]
and on the second thought (discussed with @cgreich and @mgurley as well)
decided to leave them as they are now to be consistent with the other NAACCR Variables / Values.

**Comment by mgurley** [comment]
This is done.
