### ISSUE TITLE
Create ICDO concept for 'Unknown Histology' and  precoordinate with all ICDO sites.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#67]
We have to support the case where a ICDO site will be known but no histology is known.  For example, brain tumors found on imaging but having no pathology.
Without hardcoding, how will ETL developers know to map their NULL histology values to this 'Unknown Histolgoy' ICDO concept.

**Comment by mgurley** [comment]
9999/9 - Unknown histology, and yet, we need to connect all sites to this code

**Comment by sratwani** [comment]
Dima confirmed that he's already working on this issue.

**Comment by ekorchmar** [comment]
If I understand your request correctly, we need to make sure that morphology ([8000/1](http://athena.ohdsi.org/search-terms/terms/44498000) Tumor, NOS) is available for every single topography? This code seems to exist exactly to fulfill the role for poorly specified histologies.

Although it goes against specifications of ICD-O-3 itself, some cancer registries include placeholder value of 9999/9 for unknown histologies, not necessarily even neoplasms (so they fall outside of ICD-O-3 scope). Example of local guideline specifying such code [here](https://www2.gov.scot/resource/0042/00423494.pdf) (p.49).

We could include this code and it's combinations if it is necessary to differentiate between 'unknown histology' and standard 8000/1. Is this a necessary solution for your use-case?

**Comment by dimshitc** [comment]
I suppose we have to distinguish between 8000/1 Tumor, NOS (When it is exactly documented as '8000/1');
and the case when the Histology is not reported / not documented / there's an empty field in cancer registry, and in this case we need to use 9999/9 code.

**Comment by cgreich** [comment]
Wait guys. If an attribute is not available go to a concept that doesn'T have it. Instead of an attribute called "Not there". So, in our case why would we not go to the SNOMED concept "Malignant neoplasm of XYZ", where the histology is missing?

**Comment by dimshitc** [comment]
Nice:) it was @ekorchmar 's initial thought, and then I convinced him that we need this undefined thing because of NAACCR schema definition. We'll check whether NAACCR schema definition works even we treat ICDO topography without histology as an ICD10CM code and map it to SNOMED.

**Comment by ekorchmar** [comment]
Can we really treat ICD-O-3 topgraphy codes as ICD10CM though?

ICDO3 uses topography codes from ICD-10-CM chapters with malignant neoplasms, even when neoplasm is benign or of uncertain behavior. That means that benign and malignant lesions all have the same topography codes, always corresponding to ICD-10-CM **malignant** neoplasms and we can't directly transition to using pure ICD-10-CM from topography.

We need to choose either to treat missing histologies as 8000/1 (unspecified neoplasm) or to create a new code to specifically mark them as undocumented histologies.

In first case they will get mapped to SNOMED concepts - generic neoplasms of corresponding body sites. In the second case they will become separate standard concepts and descendants of said SNOMED concepts (if undocumented histology is a distinctive enough attribute to consider them different entities). It's a matter of vocabulary design.

Also, could it be possible that histology was not documented because what was found was not a neoplasm at all? What if it was another pathology, like foreign body or aneurism? We would need to map missing histologies to 'Lesion of [organ]' then.

**Comment by cgreich** [comment]
@ekorchmar: 

- Can we really treat ICD-O-3 topgraphy codes as ICD10CM though?

What has that to do with SNOMED?

- That means that benign and malignant lesions all have the same topography codes, always corresponding to ICD-10-CM malignant neoplasms and we can't directly transition to using pure ICD-10-CM from topography.

I see your point. So, an unknown histology really means we don't know it's a benign or malignant tumor. And we don't precoordinated combos of anatomical site with "Tumor of unknown genesis", only malignant and benign, right?

If so, true. We cannot handle without creating new concepts like that. But I can'T imagine this is typical. Let's first find out of the data if we are creating a solution for a minimal problem.

**Comment by dimshitc** [comment]
About 1 third of the data have empty histology code and filled site code.
We can't treat  ICD-O-3 topgraphy codes as ICD10CM. Right.
But we can map them to SNOMED, for example C61.9 "Prostate gland", histology = null
can be mapped to 4129902 Neoplasm of prostate.
We need to distinguish this from just a topography concept C61.9. So, adding 9999/9 as a histology seems to be good.

**Comment by cgreich** [comment]
> We can map them to SNOMED, for example C61.9 "Prostate gland", histology = null
can be mapped to 4129902 Neoplasm of prostate.

Exactly. That's what I meant.

> We need to distinguish this from just a topography concept C61.9. So, adding 9999/9 as a histology seems to be good.

Don't understand. That SNOMED concept needs to be distinguished from an ICD-O-3 concept, and the way to do it is to add some null-flavory 9999/9?

**Comment by dimshitc** [comment]
> Don't understand. That SNOMED concept needs to be distinguished from an ICD-O-3 concept, and the way to do it is to add some null-flavory 9999/9?

I meant we need to distingiush ICDO 'C61.9' as a topography and ICDO 'C61.9' as a disorider.
But we don't need to create separate concepts for this. 
We need to build different relationships instead:
ICDO 'C61.9'  Maps to 4129902 Neoplasm of prostate (disorder)
ICDO 'C61.9' 'ICDO - SNOMED' Structure of prostatic gland (body site)

We also discovered histologies without topography in the data, so it makes sense to map histologies to disorders as well.

It seems like a nice solution:
We keep 'ICDO - SNOMED' relationships from ICDO site, histology to SNOMED site, histology ([we have this already](http://athena.ohdsi.org/search-terms/terms/44497896) )
and add 'Maps to' relationships from ICDO site, histology to SNOMED disorders.

**Comment by mgurley** [comment]
So from an ETL perspective, if in my NAACCR data I only have a 'C61.9' with a blank histology, is the instruction to tell me to replace my blank histology with '9999/9', so I get the following paring ICDO histology/site '9999/9-C61.9'.  This will map to an 'Condition' concept with concept_class_id = 'ICDO Condition' in the OMOP vocabulary with a concept_code='9999/9-C61.9', which will be standard concept depending on whether it can or cannot be mapped to a 'Condition' concept with concept_class_id='Clinical Finding'.

**Comment by dimshitc** [comment]
My last message was about not to add '9999/9'. Just keep 'C61.9'.
1. To identify site specific concepts in this case NAACCR we'll have :
Prostate (NAACCR Schema) - 'Schema to ICDO' - 'C61.9' 
and [histology_site ](https://github.com/OHDSI/OncologyWG/blob/master/etl/naaccr_etl.sql#L21)in this case ='C61.9' 

2. To fill the CONDITION you use this mapping

> ICDO 'C61.9' 'Maps to' 4129902 Neoplasm of prostate (disorder)

**Comment by dimshitc** [comment]
And as we're going to map ICDO attributes to SNOMED Condition, we have to change ICDO site and histology domain into 'Condition' to avoid confusion when source and target concepts have different domains.

**Comment by cgreich** [comment]
@dimshitc: You shouldn't map a Observation Concept (Topology) to a Condition Concept. Instead, you need to create "NULL-C61.9" or "-61.9" combo concepts, that you then can map to the 4129902 Neoplasm of prostate (disorder).

**Comment by dimshitc** [comment]
Instead of '9999/9-C61.9' (in the initial request) we create 'NULL-C61.9' concept. I'm Ok with that. @mgurley ?

**Comment by mgurley** [comment]
@dimshitc 
Yea that seems good to me.

**Comment by sratwani** [comment]
@dimshitc @mgurley  -> Guys, does this also cover the unknown morphology? Peter brought up that in IKNL, they have unknown morphology and Dima mentioned that he has created all possible combinations of anatomic site and unknown.
