### ISSUE TITLE
Create new 'Regimen' domain, move all the Hemonc.org regimens into the new domain, create entries in the new domain for NAACCR high-level drug concepts and non-standardize existing drug NAACCR item codes. 

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#69]
Having Hemonc.org regimens and NAACCR high-level drug concepts within the Drug domain causes problems for concept hierarchy traversal.  To get around the problems, we want to create a new 'Regimen' domain, move all the Hemonc.org regimens into the new domain, and create entries in the new domain for NAACCR high-level drug concepts.  This new 'Regimen' domain will be used in the EPISODE.episode_object_concept_id field.  We need the following high-level NAACCR drug concepts to be added to this domain:

'Chemotherapy'
'Hormone therapy'
'Immunotherapy'

The following NAACCR item code treatment concepts should stay in the Drug domain but be made non-standard:

concept_id | concept_name | concept_code| standard_concept
------------ | -------------|------------ | -------------
35915215|Chemotherapy, NOS.|1390@1
35916302|Chemotherapy, single agent.|1390@2
35918919|Chemotherapy, multiple agents.|1390@3
35918922|Hormone therapy administered as first course therapy.|1400@1
35918935|Immunotherapy administered as first course therapy.|1410@1

Entries within CONCEPT_RELATIONSHIP should be made between these NAACCR item code drug concepts and the the new domain for NAACCR high-level 'Regimen' concepts.  The relationship should not be 'Maps to', because we have two different domains but something that ETL developers can use to navigate from drug NAACCR item codes for making an entry into the EPISODE table.

**Comment by dimshitc** [comment]
Should we keep

concept_id | concept_name | concept_code | standard_concept
-- | -- | -- | --
35915215 | Chemotherapy, NOS. | 1390@1 |  
35916302 | Chemotherapy, single agent. | 1390@2 |  
35918919 | Chemotherapy, multiple agents. | 1390@3 |  
35918922 | Hormone therapy administered as first course therapy. | 1400@1 |  
35918935 | Immunotherapy administered as first course therapy. | 1410@1

as Episodes?

**Comment by mgurley** [comment]
@dimshitc 
Those concepts are all currently in the 'Drug' domain but are standard.  I think the decision was that they should stay in the 'Drug' domain but become non-standard.  Each of these concepts does have an 'Answer of' entry in the CONCEPT_RELATIONSHIP table to a concept in the 'Episode' domain.  For example, 35916302 to 35918602.  35916302 should stay in the Episode domain.

concept_id | concept_name | domain_id | standard_concept|relationship_id|concept_id | concept_name | domain_id| standard_concept
-- | -- | -- | ---- | -- | -- | --| -- | --
35918602|RX Summ--Chemo|Episode||Has Answer|35915215|Chemotherapy, NOS.|Drug|S
35918602|RX Summ--Chemo|Episode||Has Answer|35916302|Chemotherapy, single agent.|Drug|S
35918602|RX Summ--Chemo|Episode||Has Answer|35918919|Chemotherapy, multiple agents.|Drug|S
35918619|RX Summ--Hormone|Episode||Has Answer|35918922|Hormone therapy administered as first course therapy.|Drug|S
35918454|RX Summ--BRM|Episode||Has Answer|35918935|Immunotherapy administered as first course therapy.|Drug|S

**Comment by dimshitc** [comment]
Ok. You're right

**Comment by dimshitc** [comment]
Talking to @rimusia and @mgurley 
Decided to make NAACCR concepts listed as Standard Regimen.

**Comment by mgurley** [comment]
> Talking to @rimusia and @mgurley
> Decided to make NAACCR concepts listed as Standard Regimen.

And we decided to not insert NAACCR drug treatments into DRUG_EXPOSURE unless we can come up with vocabulary support that make sense.

**Comment by mgurley** [comment]
This is done.
