### ISSUE TITLE
Ingest the Nebraska lexicon into the vocabulary tables.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#7]
- Parse input. Create attribute-value relationship.
- Link to sites: breast, colon
- Replace LOINC attribute codes with SNOMED when available

**Comment by mgurley** [comment]
@dimshitc  Yes, I am a little confused about how the distribution files relate to the protocol PDF.  If we can't use the distribution files as the basis for the ingestion and need to scrape the PDF, then we have a problem.  This was why I sent the email to Scott Campbell yesterday asking about the latest version.  I thought he mentioned at AMIA that LOINC was being removed from the Nebraska Lexicon because of licensing issues.  Your layout of the concept relationships look good but we nee to talk to Scott about the distribution files.

**Comment by dimshitc** [comment]
not a problem actually for now, we already copy-pasted this information manually - it can be used in a first run.
but later we need to get some automated way of course

**Comment by dimshitc** [comment]
So, is this still actual?
Is it related somehow to CAP eCC?
Can we talk about this on the one of the vocabulary meetings?

**Comment by patelm9** [comment]
@mgurley @dimshitc I think Nebraska is key from some of our pathology mappings. What is the status of this effort? I downloaded the Nebraska files, but they weren't as intuitive as I was expecting.

**Comment by ekorchmar** [comment]
Currently the SNOMED version of Nebraska Lexicon is being under assessment for inclusion in OMOP CDM Vocabularies. It does not seem to include any crosswalks to PDF protocols.

**Comment by sratwani** [comment]
Completed as a part of the 2020 Symposium effort.
