### ISSUE TITLE
For NAACCR radiation therapy treatment variables, add a 'Variable has end date' relationship.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#71]
NAACCR radiation therapy treatment variables are unique in that they encode an 'end date' to the Episode.  Right now NAACCR item numbers 1506, 1516 and 1526 have each have two 'Variable has date' 'entries in the CONCEPT_RELATIONSHIP table to NAACCR item numbers 1210 (RX DATE RADIATION) and 3220 (RX DATE RAD ENDED).  But this makes it ambiguous which is the start and which the end.  So we need to create a new relationship and and only relate the begin date and the end dates to the right relationship.

**Comment by denyskaduk** [comment]
Hi, if we will create relationship for NAACCR item and 3220 (RX DATE RAD ENDED) -  'Variable has end date', we suggest to create newone relationship 'Variable has start date' between NAACCR item and 1210 (RX DATE RADIATION). It will give more easier ETL process when field _START_DATE and _END_DATE will filling.

**Comment by mgurley** [comment]
@denyskaduk That seems reasonable.

**Comment by cgreich** [comment]
Friends:

Hm. I am a little torn. We are trying to build the vocabulary system into a automated ETL structure, and we do that without really thinking about the model. Instead, we keep adding relationships, which are increasingly rare and odd. On the other hand I understand the intention. LEt me think about it and do a Forum post.

**Comment by dimshitc** [comment]
Actually, we are thinking about the model.
We don't have the way to determine the end date with the current model. 
So, Michael found a way to do this.

**Comment by dimshitc** [comment]
In the last CDM/Vocabulary meeting was decided that we keep 'Variable has date' relationship to both 1210 (RX DATE RADIATION) and 3220 (RX DATE RAD ENDED). Then ETL puts earliest date as a start_date, and latest - as an end date.

**Comment by dimshitc** [comment]
31 Oct we decided to use 'Variable has start date' for earliest date, 'Variable has end date' for latest date.

**Comment by sratwani** [comment]
Per the 10/31 discussion, Team agreed that this task (one relationship) will be completed by Dima. We are essentially adding relationships that should have been there but not explicitly expressed. The fact that it simplifies ETL and understanding of the data is the goal of this effort. This is where we will draw the line and any other work related to the relationships will be handled by the modeling team. Rima is working on a poster on what we have done so far and will work on a paper to introduce the community so we can engage them and receive input on how to approach this.

**Comment by denyskaduk** [comment]
We create new relationship 'Has start date' and 'Has end date'.
