### ISSUE TITLE
NAACCR Variable 1060 'TNM EDITION NUMBER' is missing NAACCR Values.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#78]
- NAACCR Variable 1060 is missing NAACCR Values.  Compare the following:
  - http://datadictionary.naaccr.org/default.aspx?c=10#1060
  - http://athena.ohdsi.org/search-terms/terms/35918875

**Comment by sratwani** [comment]
Assigned to @dimshitc , Dima and @cgreich will have a conversation about resources needed for this task.
