### ISSUE TITLE
NAACCR Variable 1117 'METS AT DX-OTHER' is missing NAACCR Values

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#79]
- NAACCR Variable 1117 'METS AT DX-OTHER' is missing NAACCR Values.  Compare the following:
  - http://datadictionary.naaccr.org/default.aspx?c=10#1117
  - http://athena.ohdsi.org/search-terms/terms/35918527

**Comment by sratwani** [comment]
Assigned to @dimshitc , Dima and @cgreich will have a conversation about resources needed for this task.
