### ISSUE TITLE
Decide how to encode the relationship within the OHDSI vocabulary tables the list of possbile condition modifiers for a given anatomic site(s).

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#8]
This will be necessary for both the Nebraska Lexicon and NAACCR.  ETL developers will need to know if I have a diagnosis/condition in anatomic site X, then give me the list of possible modifiers.
See #6 and #7.

**Comment by dimshitc** [comment]
to use FACT_RELATIONSHIP?

**Comment by dimshitc** [comment]
NAACCR.
Map their sites to SNOMED, if not possible - create a new standard concept.
then build relationships. Example.

we have the procedure code "50" for Total proctectomy in "Rectosigmoid" Site.
we create a new concept with 
concept_code = 'Proc_50_Rectosigmoid'
concept_name= 'Total proctectomy'
vocabulary_id ='NAACCR'
and build the relationships:
 'Proc_50_Rectosigmoid' | Maps to | 235364003 (Total proctectomy - SNOMED)
'Proc_50_Rectosigmoid' | Has Site (NAACCR) | 81922002 Rectosigmoid structure (SNOMED)

Is it the right way?
If it's right, I'll create the examples of the other values

**Comment by mgurley** [comment]
@dimshitc @cgreich We agreed to the approach suggested by Dima.  Just need to decide on the proper relationship(s) to use/create.
