### ISSUE TITLE
Some more NAACCR Variables missing NAACCR Values.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#81]
It is possible that this is cruft that we should curate away but right now they are standard concepts and because they have no values, they can't be ETLed:

concept_id|concept_name|concept_code
--|--|--
35918787|CS Version Input Original|2935
35918741|CS Version Derived|2936
35918293|CS Version Input Current|2937
35918766|Type of Reporting Source|500

**Comment by denyskaduk** [comment]
Hello! For Variable 'Type of Reporting Source' I found in NAACCR dictionaty values and they will be added to vocabulary: 


Variable_code | Variable_name | Value_code | Value_name
-- | -- | -- | --
500 | Type of Reporting Source | 1 | Hospital inpatient; Managed health plans with comprehensive, unified medical records
500 | Type of Reporting Source | 2 | Radiation Treatment Centers or Medical Oncology Centers (hospital-affiliated or independent)
500 | Type of Reporting Source | 3 | Laboratory only (hospital-affiliated or independent)
500 | Type of Reporting Source | 4 | Physician's office/private medical practitioner (LMD)
500 | Type of Reporting Source | 5 | Nursing/convalescent home/hospice
500 | Type of Reporting Source | 6 | Autopsy only
500 | Type of Reporting Source | 7 | Death certificate only
500 | Type of Reporting Source | 8 | Other hospital outpatient units/surgery centers

As you can see values 1-5 and 8 can be introduced as 'Visit'. We want to give this values domain_id = 'Visit' and do them as standard one, in future it can be mapped to our standard visit concepts. Values 6 and 7 seemes like as 'Type concept', but all data from NAACCR will have 'Tumor Registry' as TYPE_CONCEPT_ID, so we will keep this values as non-standard and with domain 'Meas Value'.

**Comment by dimshitc** [comment]
concept_id | concept_name | concept_code
-- | -- | --
35918787 | CS Version Input Original | 2935
35918741 | CS Version Derived | 2936
35918293 | CS Version Input Current | 2937

These should be non-standard Observation.
In this case usual ETL fills source_value fields with exact codes and standard_concept_id sets = 0.
If we delete them from the vocabulary, the same will happen.

concept_id | concept_name | concept_code
-- | -- | --
35918766 | Type of Reporting Source | 500 

contains some information. So I suggest to make it Standard Observation and its values - standard Meas Values.

@mgurley  are you agree?

**Comment by mgurley** [comment]
@dimshitc I agree that the following should be non-standard Observation.

concept_id | concept_name | concept_code
-- | -- | --
35918787 | CS Version Input Original | 2935
35918741 | CS Version Derived | 2936
35918293 | CS Version Input Current | 2937

I think the following should be Measurement standard.   Remember, most of these NAACCR items are modifying tumor characteristics.  And we added 'modifier_of_field_concept_id' and 'modifier_of_event_id' to MEASURMENT to allow for these tumor characteristics to modify their diagnosis parent.  If we put it in Observation, we will lose the connection to the diagnosis in CONDITION_OCCURRENCE or EPISODE. 

concept_id | concept_name | concept_code
-- | -- | --
35918766 | Type of Reporting Source | 500

**Comment by dimshitc** [comment]
all of them - make non standard Observation
