### ISSUE TITLE
Map NAACCR modifiers to a standardized vocabularies.  Maybe Nebrasaka Lexicon.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#9]
The idea is that in the end NAACCR will be a 'source' vocabulary and that Nebraska Lexicon will be the 'standard' vocabulary for condition/disease episodes.  This will task will be a placeholder for mapping all anatomic sites in NAACCR to all anatomic sites in the Nebraska Lexicon.  Each anatomic site or groups of anatomic sites will have separate tasks.

**Comment by dimshitc** [comment]
Should we map NAACCR and Nebraska Lexicon anatomic sites to SNOMED?
As we mapped ICDO Topography?

**Comment by mgurley** [comment]
@dimshitc Yes,I believe we should map NAACCR and  Nebraska Lexicon anatomic sites to SNOMED, like we did for ICDO topography.  All three mapping to a shared anatomic site vocabulary will allow us to move back and forth between them.

**Comment by cgreich** [comment]
Wait a minute, guys. Why are we mapping Nebraska to SNOMED? It *is* SNOMED. Or does Scott not use existing SNOMED concepts?

**Comment by mgurley** [comment]
@cgreich My hope is that you are right, but we need to talk to Scott to see how his reference files relate to his PDF and whether his attribute/value pairs (which are hopefully all in existing SNOMED or to be proposed new SNOMED concepts) relate to a parent anatomic sites.  We see in his distribution the CAP checklist for say, Invasive Breast, has all the attribute/value pairs encoded with the attribute as a LOINC code **and** a SNOMED code and the possible values encoded as SNOMED codes.  However, I don't see that the fact that these attribute/value pairs all belong to the 'Breast' anatomic site is formalized by a relationship to the SNOMED concept for the anatomic site for 'Breast'.   We are supposed to meet with Scott this week, so hopefully we will clear up these questions.

**Comment by dimshitc** [comment]
Yes, content of PDF files is partially represented in Nebraska distribution files.
But anatomical sites belong to the regular SNOMED, so yes, we don't need to map them

**Comment by mgurley** [comment]
@dimshitc 
No I have not met with Nebraska team beyond the last group meeting we had back in December. Before we can map NAACCR modifiers to Nebraska Lexicon modifiers, we need to get NAACCR and Nebraska into OMOP.  So need to complete #6 and #7.

  Right now Nebraska only covers 2 CAP Cancer checklists, Breast and Colon.  So I suggest we first get NAACCR into OMOP, then get Nebraska Breast and Colon into OMOP.  Then we will be able to attempt to map NAACCR to Nebraska Breast and Colon. 

  For Scott and Walter to finish mapping the rest of the CAP Cancer Cancer checklists to SNOMED, they said they need the help of a working pathologist familiar with each anatomic site checklist.  Approximate effort of a 2 hour meeting per CAP Cancer checklist.  So we will need to find a bunch of working pathologists willing to dedicate time.  For example, a neuropathologist actively using the CAP Primary CNS checklist, a Prostate pathologist actively using the  CAP Prostate Checklist and so on.  So we will need a person to spearhead recruiting and  scheduling the pathologists to meet with the Nebraska folks.

**Comment by cgreich** [comment]
@mgurley:

Have we made any progress on the pathologist front? Would our OMOPed NAACCR help in that process by cleaning up the duplications and ambiguities?

**Comment by mgurley** [comment]
@cgreich

No progress from my side.  We can ask @rimusia   It will require some extensive project management.  I think we should begin the regular workgroup meetings.  To enlist troops.

I believe our OMOPed NAACCR would help in the process of cleaning up duplication and ambiguities.   NAACCR covers all (if sloppily) anatomic sites and is discrete and available within many institutions.  The CAP Cancer Checklists are beautiful but most often trapped in textual narratives, so the Nebraska lexicon will be a great eventual target but we need NAACCR now to be able to at least represent what is readily available.

**Comment by mgurley** [comment]
Too broad in scope.
