### ISSUE TITLE
Bring in the ICDO3 Topography Classes into the OMOP vocabulary.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#96]
https://bioportal.bioontology.org/ontologies/ICD-O-3-T/?p=classes&conceptid=root

This class hierarchy structure is very close to how most oncology researchers broadly categorize major cancer types.  OMOP data should be able to meet those expectations.

**Comment by cgreich** [comment]
@dimshitc: can you show?

**Comment by mgurley** [comment]
Ah, I see that C50 'Subsumes the' following

- C50 | breast
  - C50.1 | Central portion of breast
  - C50.2 | Upper-inner quadrant of breast
  - C50.3 | Lower-inner quadrant of breast
  - C50.4 | Upper-outer quadrant of breast
  - C50.5 | Lower-outer quadrant of breast
  - C50.6 | Axillary tail of breast
  - C50.8 | Overlapping lesion of breast
  - C50.9 | Breast, NOS

But as their equivalents in ICD10CM.
